import Link from "next/link";
import { Activity, ArrowLeft, CheckCircle2, Database, Server, ShieldAlert, Sparkles } from "lucide-react";
import { calculateProgress, getModuleAudit, progressFormula } from "@/lib/system-status";
import "./status.css";

export const dynamic="force-dynamic";

export default function SystemStatusPage(){
  const modules=getModuleAudit(); const progress=calculateProgress(modules); const checked=new Date().toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short",timeZone:"Europe/Paris"});
  return <main className="status-page"><header><Link href="/app/securite"><ArrowLeft/> Retour à Nova</Link><span><Sparkles/> NOVA SYSTEM STATUS</span><h1>État technique réel</h1><p>Ce tableau distingue explicitement les interfaces de démonstration des fonctionnalités persistantes et réellement intégrées.</p></header><section className="status-overview"><div className="status-ring" style={{"--progress":`${progress*3.6}deg`} as React.CSSProperties}><strong>{progress}%</strong><small>Overall Progress</small></div><div><span>MÉTHODE DE CALCUL</span><h2>{modules.length} modules audités</h2><p>{progressFormula}</p><div className="status-counts">{(["WORKING","PARTIAL","DEMO","MISSING","BLOCKED"] as const).map(status=><b className={status.toLowerCase()} key={status}>{modules.filter(item=>item.status===status).length} {status}</b>)}</div></div><aside><Database/><span><b>{process.env.DATABASE_URL?"PostgreSQL configuré":"PostgreSQL non configuré"}</b><small>{process.env.DATABASE_URL?"Connexion déclarée":"DATABASE_URL absente"}</small></span></aside></section><section className="status-table"><header><span>MODULE</span><span>STATUS</span><span>FRONTEND</span><span>BACKEND</span><span>DATABASE</span><span>AI</span><span>INTEGRATION</span><span>LAST CHECK</span><span>NOTES</span></header>{modules.map(item=><article key={item.module}><b>{item.module}</b><em className={item.status.toLowerCase()}>{item.status}</em>{[item.frontend,item.backend,item.database,item.ai,item.integration].map((value,index)=><i className={value?"yes":"no"} key={index}>{value?<CheckCircle2/>:<ShieldAlert/>}</i>)}<time>{checked}</time><p>{item.notes}</p></article>)}</section><footer><Server/><span><b>Statut généré depuis la configuration du déploiement</b><small>Aucune réponse HTTP 200 n’est assimilée automatiquement à une fonctionnalité opérationnelle.</small></span><Activity/></footer></main>;
}
