import type { Metadata } from "next";
import { ArrowDown, ArrowRight, Check, CircleDot } from "lucide-react";
import { categories } from "@/components/data";
import { CTA, PageHero, Reveal } from "@/components/ui";
export const metadata:Metadata={title:"Automatisations",description:"Découvrez les workflows métier que NOVA peut orchestrer avec vos outils et vos règles."};
const flows = [
  ["Pipeline commercial",["Nouveau lead détecté","Nova qualifie le contexte","CRM mis à jour","Email personnalisé préparé","Suivi planifié","Commercial informé"]],
  ["Clôture mensuelle",["Pièces collectées","Données rapprochées","Anomalies signalées","Rapport préparé","Validation demandée","Synthèse distribuée"]],
  ["Support client",["Message reçu","Intention identifiée","Historique consulté","Réponse proposée","Escalade si nécessaire","Satisfaction suivie"]],
];
export default function Automatisations(){return <><PageHero kicker="Automatisations" title="Vos processus avancent." accent="Même quand vous changez de sujet." text="NOVA relie les déclencheurs, les agents, vos outils et vos règles de validation dans des workflows lisibles."/><section className="section"><div className="shell"><Reveal className="section-heading"><span className="eyebrow">Tous les métiers, une logique commune</span><h2>Choisissez un résultat.<br/><em>Nova orchestre le chemin.</em></h2></Reveal><div className="category-grid">{categories.map(([name,Icon],i)=><Reveal className="category-card" key={name}><span>0{i+1}</span><Icon/><h3>{name}</h3><p>Des déclencheurs aux actions, avec permissions et validation.</p><ArrowRight/></Reveal>)}</div></div></section><section className="section workflow-section"><div className="shell"><Reveal className="section-heading centered"><span className="eyebrow light">Workflows transparents</span><h2>Voyez exactement<br/><em>ce qui se passe ensuite.</em></h2></Reveal><div className="workflow-grid">{flows.map(([name,steps],f)=><Reveal className="workflow-card" key={name as string}><div className="workflow-title"><CircleDot/><span>WORKFLOW 0{f+1}</span><b>{name as string}</b></div>{(steps as string[]).map((step,i)=><div className="workflow-step" key={step}><span>{i<5?<Check/>:<CircleDot/>}</span><p>{step}</p>{i<5&&<ArrowDown/>}</div>)}<button className="workflow-button">Adapter ce workflow <ArrowRight/></button></Reveal>)}</div></div></section><CTA title="Un processus répétitif ? Donnez-le à Nova." text="Commencez par un workflow. Étendez ensuite l’orchestration à toute l’entreprise."/></>}
