import { neon } from "@neondatabase/serverless";
const base=process.env.NOVA_E2E_BASE_URL||"https://guyf.vercel.app",sql=neon(process.env.DATABASE_URL),run=`p2gj-${Date.now()}`,password=`Nova-${run}-Secure!`,orgIds=[],userIds=[],results=[];
class Jar{constructor(){this.c=new Map()}cookie(){return [...this.c].map(([k,v])=>`${k}=${v}`).join("; ")}async req(path,options={}){const r=await fetch(base+path,{cache:"no-store",redirect:"manual",signal:AbortSignal.timeout(20000),...options,headers:{Origin:base,"Content-Type":"application/json",...(this.cookie()?{Cookie:this.cookie()}:{}),...(options.headers||{})}});for(const raw of r.headers.getSetCookie?.()||[]){const [p]=raw.split(";");const i=p.indexOf("=");this.c.set(p.slice(0,i),p.slice(i+1))}return {r,p:await r.json().catch(()=>({}))}}}
const A=new Jar(),B=new Jar(),V=new Jar();const ok=(name,condition,detail)=>{if(!condition)throw new Error(`${name}: ${detail}`);results.push({test:name,status:"PASS",detail});console.log(`PASS ${name} — ${detail}`)};
async function signup(j,name,email){const x=await j.req("/api/auth/sign-up/email",{method:"POST",body:JSON.stringify({name,email,password})});if(!x.r.ok)throw new Error(`signup ${x.r.status}`);userIds.push(x.p.user.id);return x.p.user}async function org(j,name){const x=await j.req("/api/organizations",{method:"POST",body:JSON.stringify({name,industry:"E2E",country:"France",language:"fr",timezone:"Europe/Paris"})});orgIds.push(x.p.data.id);return x.p.data}async function invite(from,to,role){const x=await from.req("/api/invitations",{method:"POST",body:JSON.stringify({email:to.email,role})});const token=x.p.acceptUrl.split("/").pop();const accepted=await to.jar.req("/api/invitations/accept",{method:"POST",body:JSON.stringify({token})});if(!accepted.r.ok)throw new Error(`invite accept ${accepted.r.status}`);return x.p.data}
try{const ua=await signup(A,"Switch User",`${run}-a@example.com`),ub=await signup(B,"Owner B",`${run}-b@example.com`),uv=await signup(V,"Viewer",`${run}-v@example.com`);ua.jar=A;ub.jar=B;uv.jar=V;const oa=await org(A,`GJ A ${run}`),ob=await org(B,`GJ B ${run}`);const [ca,da,cb,db]=await Promise.all([A.req("/api/crm/contacts",{method:"POST",body:JSON.stringify({firstName:"A",lastName:"Tenant",company:"A",email:`a-${run}@example.com`,status:"new",source:"e2e",tags:[]})}),A.req("/api/crm/deals",{method:"POST",body:JSON.stringify({title:"Deal A",company:"A",value:1000,stage:"new",probability:10})}),B.req("/api/crm/contacts",{method:"POST",body:JSON.stringify({firstName:"B",lastName:"Tenant",company:"B",email:`b-${run}@example.com`,status:"new",source:"e2e",tags:[]})}),B.req("/api/crm/deals",{method:"POST",body:JSON.stringify({title:"Deal B",company:"B",value:2000,stage:"new",probability:10})})]);
  await invite(B,ua,"MEMBER");await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:oa.id})});const listA=await A.req("/api/crm/contacts");await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:ob.id})});const [listB,dealsB]=await Promise.all([A.req(`/api/crm/contacts?refresh=${Date.now()}`),A.req(`/api/crm/deals?refresh=${Date.now()}`)]);ok("G — Org Switcher",listA.p.data.some(x=>x.id===ca.p.data.id)&&!listA.p.data.some(x=>x.id===cb.p.data.id)&&listB.p.data.some(x=>x.id===cb.p.data.id)&&!listB.p.data.some(x=>x.id===ca.p.data.id)&&dealsB.p.data.some(x=>x.id===db.p.data.id)&&!dealsB.p.data.some(x=>x.id===da.p.data.id),"switch A→B et refresh isolent totalement contacts et deals");
  await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:oa.id})});await invite(A,uv,"VIEWER");const members=await A.req("/api/members");const vm=members.p.data.find(x=>x.userId===uv.id),owner=members.p.data.find(x=>x.userId===ua.id);const [self,other]=await Promise.all([V.req(`/api/members/${vm.id}`,{method:"PATCH",body:JSON.stringify({role:"OWNER"})}),V.req(`/api/members/${owner.id}`,{method:"PATCH",body:JSON.stringify({role:"VIEWER"})})]);ok("I — Role Escalation",self.r.status===403&&other.r.status===403,"Viewer ne peut modifier aucun rôle, y compris le sien");
  await A.req(`/api/members/${vm.id}`,{method:"PATCH",body:JSON.stringify({role:"MEMBER"})});const contact=await A.req("/api/crm/contacts",{method:"POST",body:JSON.stringify({firstName:"Audit",lastName:"Test",company:"Audit",email:`audit-${run}@example.com`,status:"new",source:"e2e",tags:[]})});await A.req(`/api/crm/deals/${da.p.data.id}`,{method:"PATCH",body:JSON.stringify({probability:55})});const security=await A.req("/api/security");const actions=new Set(security.p.data.auditLogs.map(x=>x.action));ok("J — Audit",contact.r.ok&&["contact.created","deal.updated","member.invited","member.role_changed"].every(a=>actions.has(a))&&security.p.data.auditLogs.every(x=>x.organizationId===oa.id),"contact, deal, invitation et rôle journalisés dans le tenant A");console.table(results);console.log(JSON.stringify({run,passed:results.length,failed:0,results},null,2))
}catch(e){console.error(e);process.exitCode=1}finally{for(const id of orgIds)await sql`delete from organizations where id=${id}`.catch(()=>{});for(const id of userIds)await sql`delete from "user" where id=${id}`.catch(()=>{})}
