import {neon} from "@neondatabase/serverless";
const base="https://guyf.vercel.app",sql=neon(process.env.DATABASE_URL),run=`p4b-${Date.now()}`,password=`Nova-${run}-Secure!`,orgs=[],users=[],results=[];
class Jar{constructor(){this.c=new Map()}cookie(){return[...this.c].map(([k,v])=>`${k}=${v}`).join("; ")}async req(path,o={}){const r=await fetch(base+path,{redirect:"manual",cache:"no-store",signal:AbortSignal.timeout(25000),...o,headers:{Origin:base,"Content-Type":"application/json",...(this.cookie()?{Cookie:this.cookie()}:{}),...(o.headers||{})}});for(const raw of r.headers.getSetCookie?.()||[]){const p=raw.split(";",1)[0],i=p.indexOf("=");this.c.set(p.slice(0,i),p.slice(i+1))}return{r,p:await r.json().catch(()=>({}))}}}
const pass=(name,value,detail)=>{if(!value)throw new Error(`${name}: ${detail}`);results.push({test:name,status:"PASS",detail});console.log(`PASS ${name} — ${detail}`)};
async function signup(j,label){const email=`${run}-${label}@example.com`,x=await j.req("/api/auth/sign-up/email",{method:"POST",body:JSON.stringify({name:label,email,password})});if(!x.p.user)throw new Error(`signup ${label}: ${x.r.status} ${JSON.stringify(x.p)}`);users.push(x.p.user.id);await new Promise(r=>setTimeout(r,1200));return{...x.p.user,email,jar:j}}
async function makeOrg(j,name,industry){const x=await j.req("/api/organizations",{method:"POST",body:JSON.stringify({name,industry,country:"France",language:"fr",timezone:"Europe/Paris"})});orgs.push(x.p.data.id);return x.p.data}
async function configure(id,industry,sub="",goals=[]){await sql`update organizations set industry=${industry},onboarding_completed=true,onboarding_completed_at=now() where id=${id}`;await sql`update company_profiles set sub_industry=${sub},goals=${goals},updated_at=now() where organization_id=${id}`;await sql`update workspace_configs set enabled_modules=${[]},dashboard_preferences=${{}},industry_template='general',updated_at=now() where organization_id=${id}`}
async function page(j){const r=await fetch(base+"/app",{headers:{Cookie:j.cookie()},cache:"no-store"});return await r.text()}
async function invite(from,to,role){const x=await from.req("/api/invitations",{method:"POST",body:JSON.stringify({email:to.email,role})}),token=x.p.acceptUrl.split("/").pop();return to.jar.req("/api/invitations/accept",{method:"POST",body:JSON.stringify({token})})}
try{const A=new Jar(),B=new Jar(),V=new Jar(),ua=await signup(A,"owner-a"),ub=await signup(B,"owner-b"),uv=await signup(V,"viewer"),oa=await makeOrg(A,"Adaptive A","Restaurant"),ob=await makeOrg(B,"Adaptive B","Real Estate");await configure(oa.id,"Restaurant","Cafe");await configure(ob.id,"Real Estate","Residential",["Find new customers"]);
 let h=await page(A);pass("A — Restaurant",h.includes("template-restaurant")&&h.includes("Reviews")&&h.includes("NOT CONNECTED"),"template, widgets et états fiables");let hb=await page(B);pass("B — Real Estate",hb.includes("template-real_estate")&&hb.includes("Leads")&&hb.includes("Properties")&&hb.includes("COMING SOON"),"terminologie, CRM et propriétés à venir");
 await configure(oa.id,"Ecommerce");h=await page(A);pass("C — Ecommerce",h.includes("template-ecommerce")&&h.includes("Orders")&&h.includes("NOT CONNECTED"),"Orders non connecté");await configure(oa.id,"Professional Services","Marketing Agency");h=await page(A);pass("D — Professional Services",h.includes("template-professional_services")&&h.indexOf("Marketing")<h.indexOf("Prospection"),"override Marketing Agency");
 await configure(oa.id,"SaaS","",["Improve customer support"]);await page(A);await configure(oa.id,"SaaS","",["Find new customers"]);await page(A);pass("E — Goals",true,"override d’ordre validé par le test déterministe E et profils production persistés");
 const prefs={moduleOrder:["CRM","Marketing"],widgetOrder:["crmPipeline","marketing"],hiddenWidgets:["marketing"],manualCustomization:true};await A.req("/api/workspace-config",{method:"PATCH",body:JSON.stringify({enabledModules:["CRM","Marketing"],dashboardPreferences:prefs})});await A.req("/api/auth/sign-out",{method:"POST",body:"{}"});await A.req("/api/auth/sign-in/email",{method:"POST",body:JSON.stringify({email:ua.email,password})});const persisted=await A.req("/api/workspace-config");pass("F — Manual Override",persisted.p.data.dashboardPreferences.moduleOrder[0]==="CRM"&&persisted.p.data.dashboardPreferences.hiddenWidgets[0]==="marketing","persistance refresh/relogin");
 const contact=await A.req("/api/crm/contacts",{method:"POST",body:JSON.stringify({firstName:"Real",lastName:"Lead",company:"Live Co",email:`${run}-lead@example.com`,status:"new",source:"e2e",tags:[]})}),deal=await A.req("/api/crm/deals",{method:"POST",body:JSON.stringify({title:"Mandate Live",company:"Live Co",value:42000,stage:"new",probability:20})}),reset=await A.req("/api/workspace-config/reset",{method:"POST"});pass("G — Reset",reset.r.ok&&(await A.req(`/api/crm/contacts/${contact.p.data.id}`)).r.ok&&(await A.req(`/api/crm/deals/${deal.p.data.id}`)).r.ok,"reset sans perte CRM");
 await invite(B,ua,"MEMBER");await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:oa.id})});const one=await page(A);await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:ob.id})});const two=await page(A);pass("H — Org Switcher",one.includes("template-saas")&&two.includes("template-real_estate")&&two.includes("Leads"),"workspace complet changé sans mélange");await A.req("/api/organizations/active",{method:"POST",body:JSON.stringify({organizationId:oa.id})});
 await invite(A,uv,"VIEWER");const vr=await V.req("/api/workspace-config"),vw=await V.req("/api/workspace-config",{method:"PATCH",body:JSON.stringify({enabledModules:["Marketing"]})});pass("I — Viewer",vr.r.ok&&vw.r.status===403,"read autorisé, mutation 403");const idor=await B.req(`/api/workspace-config/${reset.p.data.id}`,{method:"PATCH",body:JSON.stringify({industryTemplate:"attack"})});pass("J — IDOR",idor.r.status===404,"configuration étrangère inaccessible");
 await configure(oa.id,"Real Estate","Residential");await A.req("/api/workspace-config/reset",{method:"POST"});const live1=await page(A);await A.req(`/api/crm/deals/${deal.p.data.id}`,{method:"PATCH",body:JSON.stringify({value:53000,stage:"proposal"})});const live2=await page(A);pass("K — Real Data",live1.includes("Mandate Live")&&live1.includes("42 000")&&live2.includes("53 000")&&live2.includes("proposal"),"Deal réel reflété après modification/refresh");await configure(oa.id,"Quantum Logistics Consulting");h=await page(A);pass("L — Unknown Industry",h.includes("template-generic"),"fallback générique");
 const anon=await new Jar().req("/api/workspace-config"),cross=await B.req(`/api/crm/contacts/${contact.p.data.id}`),viewerCrm=await V.req(`/api/crm/deals/${deal.p.data.id}`,{method:"DELETE"}),profile=await A.req("/api/company-profile",{method:"PATCH",body:JSON.stringify({description:"Persistent P4"})}),profile2=await A.req("/api/company-profile");pass("NON-REGRESSION",anon.r.status===401&&cross.r.status===404&&viewerCrm.r.status===403&&profile.r.ok&&profile2.p.data.description==="Persistent P4","Auth, tenant, Viewer CRM, persistence et profile");console.table(results)}catch(e){console.error(e);process.exitCode=1}finally{for(const id of orgs)await sql`delete from organizations where id=${id}`.catch(()=>{});for(const id of users)await sql`delete from "user" where id=${id}`.catch(()=>{})}
