import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { requireContext } from "@/lib/auth/context";
import { getDb } from "@/lib/db";
import { novaConversations } from "@/lib/db/schema";
import { getConversation, loadMessages } from "@/lib/nova/conversations";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const access=await requireContext(request);if(access.response)return access.response;const {id}=await params;if(!z.string().uuid().safeParse(id).success)return Response.json({error:"NOT_FOUND"},{status:404});const conversation=await getConversation(access.context!,id);if(!conversation)return Response.json({error:"NOT_FOUND"},{status:404});return Response.json({data:{conversation,messages:await loadMessages(id)}})}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const access=await requireContext(request);if(access.response)return access.response;const {id}=await params,body=await request.json().catch(()=>({}));const parsed=z.object({title:z.string().trim().min(1).max(100).optional(),archived:z.boolean().optional()}).safeParse(body);if(!parsed.success)return Response.json({error:"INVALID_REQUEST"},{status:400});const existing=await getConversation(access.context!,id);if(!existing)return Response.json({error:"NOT_FOUND"},{status:404});const [updated]=await getDb().update(novaConversations).set({...(parsed.data.title?{title:parsed.data.title}:{}),...(parsed.data.archived!==undefined?{archivedAt:parsed.data.archived?new Date():null}:{}),updatedAt:new Date()}).where(and(eq(novaConversations.id,id),eq(novaConversations.organizationId,access.context!.organization.id),eq(novaConversations.userId,access.context!.user.id))).returning();return Response.json({data:updated})}
export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const access=await requireContext(request);if(access.response)return access.response;const {id}=await params;const existing=await getConversation(access.context!,id);if(!existing)return Response.json({error:"NOT_FOUND"},{status:404});await getDb().delete(novaConversations).where(and(eq(novaConversations.id,id),eq(novaConversations.organizationId,access.context!.organization.id),eq(novaConversations.userId,access.context!.user.id)));return new Response(null,{status:204})}
