export type IntegrationRecommendation={name:string;status:"NOT_CONNECTED"};
export type RecommendationOutput={recommendedModules:string[];recommendedAgents:string[];recommendedAutomations:string[];recommendedIntegrations:IntegrationRecommendation[];industryTemplate:string;reasoning:string[]};
export type RecommendationInput={industry?:string|null;goals?:string[];currentTools?:Record<string,string[]>;communicationChannels?:string[];timeConsumingProcesses?:string[];departments?:string[]};
const norm=(v?:string|null)=>(v||"").toLowerCase().replace(/[ -]+/g,"_");
export function recommendWorkspace(input:RecommendationInput):RecommendationOutput{
 const modules=new Set(["Dashboard","CRM"]),agents=new Set<string>(),automations=new Set<string>(),integrations=new Set<string>(),reasons:string[]=[];const industry=norm(input.industry);let industryTemplate="general";
 if(industry.includes("restaurant")){industryTemplate="restaurant";["Customer Support","Social","Finance","Operations"].forEach(x=>modules.add(x));agents.add("Customer Support Agent");automations.add("Review & Reservation Follow-up");reasons.push("Restaurant operations benefit from support, social presence and daily operational visibility.")}
 else if(industry.includes("real_estate")||industry.includes("immobilier")){industryTemplate="real_estate";["Prospection","Documents","Calendar"].forEach(x=>modules.add(x));agents.add("Real Estate Prospecting Agent");automations.add("Property Lead Qualification");reasons.push("Real estate teams need lead follow-up, documents and appointment coordination.")}
 else if(industry.includes("ecommerce")||industry.includes("retail")){industryTemplate="commerce";["Customer Support","Marketing","Operations","Finance"].forEach(x=>modules.add(x));agents.add("Commerce Support Agent");automations.add("Order Support Triage");reasons.push("Commerce businesses need customer, order and revenue coordination.")}
 for(const goal of input.goals||[]){const g=norm(goal);if(g.includes("find_new_customers")||g.includes("increase_sales")){modules.add("Prospection");agents.add("Prospecting Agent");automations.add("Lead Qualification");reasons.push("Recommended because acquiring customers is a selected objective.")}if(g.includes("customer_support")){modules.add("Customer Support");modules.add("Communications");agents.add("Support Agent");reasons.push("Recommended because improving customer support is a selected objective.")}if(g.includes("financial")){modules.add("Finance");automations.add("Financial Reporting")}if(g.includes("marketing")){modules.add("Marketing");agents.add("Marketing Agent")}if(g.includes("employee")){modules.add("HR")}if(g.includes("operations")){modules.add("Operations")}}
 for(const process of input.timeConsumingProcesses||[]){const p=norm(process);if(p.includes("invoic")){modules.add("Finance");automations.add("Invoice Automation");reasons.push("Recommended because invoicing is a time-consuming process.")}if(p.includes("prospect")||p.includes("lead")||p.includes("follow")){modules.add("Prospection");automations.add("Prospecting Follow-up")}if(p.includes("support")){modules.add("Customer Support");agents.add("Support Agent")}if(p.includes("report")){modules.add("Analytics");automations.add("Weekly Reporting")}}
 Object.values(input.currentTools||{}).flat().forEach(x=>integrations.add(x));(input.communicationChannels||[]).filter(x=>["WhatsApp","Email","Slack","Microsoft Teams"].includes(x)).forEach(x=>integrations.add(x));
 return{recommendedModules:[...modules],recommendedAgents:[...agents],recommendedAutomations:[...automations],recommendedIntegrations:[...integrations].map(name=>({name,status:"NOT_CONNECTED"})),industryTemplate,reasoning:reasons.length?reasons:["A focused general workspace is recommended from the information provided."]};
}
