import Link from "next/link";
import { ArrowRight, Check, LockKeyhole, Network, Quote, ShieldCheck, Sparkles } from "lucide-react";
import { CTA, Hero, NovaDemo, Reveal, VoiceFlow, WeeklyDebrief } from "@/components/ui";
import { agents } from "@/components/data";

export default function Home() { return <>
  <Hero />
  <div className="logo-strip"><div className="shell"><span>CONÇU POUR COORDONNER</span>{["VENTES","FINANCE","MARKETING","SUPPORT","OPÉRATIONS"].map(x=><b key={x}>{x}</b>)}</div></div>
  <VoiceFlow />
  <WeeklyDebrief />
  <section id="produit" className="section steps"><div className="shell"><Reveal className="section-heading"><span className="eyebrow">Une seule intelligence</span><h2>De la demande<br/><em>au travail accompli.</em></h2><p>NOVA ne remplace pas vos outils. Elle crée la couche intelligente qui les fait travailler ensemble.</p></Reveal><div id="fonctionnement" className="step-grid">{[["01","Demandez","Parlez ou écrivez naturellement."],["02","Nova comprend","L’intention, le contexte et les autorisations."],["03","Les agents travaillent","Chaque mission va au bon spécialiste."],["04","Votre entreprise avance","Les actions progressent dans vos outils connectés."]].map(([n,t,d])=><Reveal className="step-card" key={n}><span>{n}</span><div className="step-icon"><i/><Sparkles/></div><h3>{t}</h3><p>{d}</p></Reveal>)}</div></div></section>
  <NovaDemo />
  <section id="agents" className="section agents-section"><div className="shell"><Reveal className="section-heading split"><div><span className="eyebrow">L’équipe qui ne dort jamais</span><h2>Des agents experts.<br/><em>Un cap commun.</em></h2></div><p>Chaque agent est spécialisé. NOVA Executive garde une vue d’ensemble, arbitre et soumet les décisions sensibles à votre validation.</p></Reveal><div className="agent-grid">{agents.map(([name,desc,Icon],i)=><Reveal className={`agent-card a${i}`} key={name}><div className="agent-head"><span>0{i+1}</span><Icon/></div><div className="agent-pulse"><i/><i/><i/></div><h3>{name}</h3><p>{desc}</p><Link href="/automatisations">Explorer <ArrowRight/></Link></Reveal>)}</div></div></section>
  <section className="section integration-preview"><div className="shell"><Reveal className="integration-stage"><div className="integration-copy"><span className="eyebrow light">Votre stack. Enfin synchronisée.</span><h2>Une intelligence<br/>au-dessus de vos outils.</h2><p>Connectez vos applications selon leur disponibilité. NOVA orchestre les flux sans masquer les permissions ni les étapes d’approbation.</p><Link className="button white" href="/integrations">Explorer les intégrations <ArrowRight/></Link></div><div className="integration-orbits"><div className="io-core">N</div>{["W","G","S","N","H","C","A","+"] .map((x,i)=><i key={i} style={{"--i":i} as React.CSSProperties}>{x}</i>)}</div></Reveal></div></section>
  <section className="section security-preview"><div className="shell security-grid"><Reveal><span className="eyebrow">Contrôle par conception</span><h2>Puissante.<br/><em>Jamais hors cadre.</em></h2><p>Définissez qui peut demander, approuver et exécuter. Les actions sensibles peuvent rester suspendues jusqu’à validation humaine.</p><Link className="text-link" href="/securite">Découvrir la sécurité <ArrowRight/></Link></Reveal><Reveal className="approval-card"><div className="approval-top"><ShieldCheck/><span>ACTION SENSIBLE</span></div><h3>Envoyer 12 relances commerciales ?</h3><p>Préparées par Nova Sales · Données CRM vérifiées</p><div className="approval-meta"><span><LockKeyhole/> Validation dirigeant requise</span><span><Network/> Journalisée</span></div><div className="approval-actions"><button>Revoir</button><button>Approuver <Check/></button></div></Reveal></div></section>
  <section className="section social-proof"><div className="shell"><Reveal className="section-heading split"><div><span className="eyebrow">Scénarios d’impact</span><h2>Moins de coordination.<br/><em>Plus d’élan.</em></h2></div><p>Découvrez comment NOVA transforme le quotidien de trois profils d’entreprise, de la demande initiale au résultat opérationnel.</p></Reveal><div className="proof-stats">{[["12 h","de coordination potentiellement libérées / sem."],["4,8×","plus rapide du brief au reporting"],["92 %","des tâches répétitives identifiables"]].map(([n,l])=><Reveal key={n}><strong>{n}</strong><span>{l}</span><small>IMPACT ESTIMÉ</small></Reveal>)}</div><div className="testimonial-grid">{[["Une seule demande coordonne les ventes, les opérations et la finance, sans perdre le fil entre les outils.","01","Direction","PME multiservice","PILOTER"],["Le brief marketing devient une suite d’actions préparées : contenu, calendrier, diffusion et mesure.","02","Marketing","Marque e-commerce","ACCÉLÉRER"],["Les actions sensibles restent lisibles et validables, pendant que les tâches répétitives avancent automatiquement.","03","Opérations","Entreprise en croissance","CONTRÔLER"]].map(([quote,initials,name,role,company])=><Reveal className="testimonial-card" key={company}><div className="testimonial-top"><Quote/><span className="scenario-tag">CAS D’USAGE</span></div><blockquote>{quote}</blockquote><div className="testimonial-person"><span>{initials}</span><div><b>{name}</b><small>{role}</small></div><em>{company}</em></div></Reveal>)}</div><div className="fictional-logos"><span>CONÇU POUR</span>{["DIRIGEANTS","VENTES","MARKETING","FINANCE","SUPPORT","OPS"].map(x=><b key={x}>{x}</b>)}</div></div></section>
  <section className="section"><div className="shell"><Reveal className="section-heading split"><div><span className="eyebrow">Des plans qui évoluent avec vous</span><h2>Commencez petit.<br/><em>Orchestrez grand.</em></h2></div><Link className="button ghost" href="/tarifs">Voir tous les tarifs <ArrowRight/></Link></Reveal><div className="pricing-preview"><div><span>STARTER</span><strong>39 €<small>/mois</small></strong><p>L’essentiel pour faire avancer une petite structure.</p></div><div className="featured"><span>PRO · LE PLUS CHOISI</span><strong>169 €<small>/mois</small></strong><p>Plus d’agents, de workflows et de capacité.</p></div><div><span>ENTERPRISE</span><strong>Sur devis</strong><p>Sécurité et orchestration sur mesure.</p></div></div></div></section>
  <CTA title="Votre entreprise attend moins. Elle avance plus." text="Une instruction suffit pour mettre toute une équipe d’agents en mouvement." label="Essayer Nova" />
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"SoftwareApplication",name:"NOVA",applicationCategory:"BusinessApplication",operatingSystem:"Web",description:"Couche d’orchestration d’agents IA pour les entreprises",offers:{"@type":"Offer",price:"39",priceCurrency:"EUR"}})}}/>
 </>; }
