"use client";
import { Search, X, ArrowUpRight } from "lucide-react";
import { useMemo, useState } from "react";
const data = [
 ["WhatsApp","Communication","Beta"],["Gmail","Communication","Beta"],["Outlook","Communication","Bientôt"],["Slack","Communication","Bientôt"],["Microsoft Teams","Communication","Bientôt"],["Discord","Communication","Bientôt"],
 ["Google Calendar","Productivité","Beta"],["Google Drive","Productivité","Beta"],["Google Sheets","Productivité","Beta"],["Notion","Productivité","Beta"],["Trello","Productivité","Bientôt"],["Asana","Productivité","Bientôt"],["Monday","Productivité","Bientôt"],["ClickUp","Productivité","Bientôt"],["Dropbox","Productivité","Bientôt"],["OneDrive","Productivité","Bientôt"],["Calendly","Productivité","Bientôt"],["Zoom","Productivité","Bientôt"],["Google Meet","Productivité","Bientôt"],["DocuSign","Productivité","Bientôt"],
 ["HubSpot","CRM","Beta"],["Salesforce","CRM","Bientôt"],["Airtable","CRM","Bientôt"], ["Stripe","Finance","Beta"],["QuickBooks","Finance","Bientôt"],["Xero","Finance","Bientôt"],
 ["Shopify","Commerce","Beta"],["WooCommerce","Commerce","Bientôt"],["WordPress","Commerce","Bientôt"], ["LinkedIn","Marketing","Bientôt"],["Instagram","Marketing","Bientôt"],["Facebook","Marketing","Bientôt"],["TikTok","Marketing","Bientôt"],["Google Ads","Marketing","Bientôt"],["Meta Ads","Marketing","Bientôt"],
 ["Zapier","Automatisation","Beta"],["Make","Automatisation","Beta"],["GitHub","Développement","Beta"],["GitLab","Développement","Bientôt"]
] as const;
export function IntegrationsExplorer(){const [q,setQ]=useState("");const [cat,setCat]=useState("Tous");const [modal,setModal]=useState<(typeof data)[number]|null>(null);const cats=["Tous",...Array.from(new Set(data.map(x=>x[1])))];const filtered=useMemo(()=>data.filter(x=>(cat==="Tous"||x[1]===cat)&&x[0].toLowerCase().includes(q.toLowerCase())),[q,cat]);return <><div className="integration-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher une intégration"/></label><div className="filters">{cats.map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div></div><div className="integration-grid">{filtered.map((item,i)=><button className="integration-card" onClick={()=>setModal(item)} key={item[0]}><span className="integration-letter">{item[0][0]}</span><div><b>{item[0]}</b><small>{item[1]}</small></div><em className={item[2]==="Beta"?"beta":"soon"}>{item[2]}</em><ArrowUpRight/></button>)}</div>{!filtered.length&&<div className="empty-state">Aucune intégration ne correspond à votre recherche.</div>}{modal&&<div className="modal-backdrop" role="presentation" onClick={()=>setModal(null)}><div className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)} aria-label="Fermer"><X/></button><span className="integration-letter big">{modal[0][0]}</span><span className="eyebrow">{modal[1]}</span><h2>{modal[0]}</h2><p>Connecteur en statut <strong>{modal[2]}</strong>. Les fonctionnalités exactes, autorisations et dates seront confirmées avant activation.</p><div className="modal-note">Aucune connexion réelle n’est activée depuis cette démonstration du site.</div><a className="button primary" href={`mailto:integrations@nova.ai?subject=${encodeURIComponent("Intégration "+modal[0])}`}>Manifester mon intérêt <ArrowUpRight/></a></div></div>}</>}
