"use client";

import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Bell, Bot, Brain, BriefcaseBusiness, Building2, ChevronDown, ChevronsLeft, CircleDollarSign, Command, CreditCard, FileText, Headphones, HelpCircle, Home, Inbox, LogOut, Megaphone, Menu, Mic2, Monitor, Package, Plug, Search, Settings, ShieldCheck, ShoppingBag, Sparkles, Target, Users, Workflow, X, Zap } from "lucide-react";
import { authClient } from "@/lib/auth/client";

const groups = [
  { name:"COMMAND", items:[["Accueil","/app",Home],["Nova","/app/assistant",Sparkles],["Nova Manager","/app/nova-manager",Command],["Autopilot","/app/autopilot",Zap]] },
  { name:"REVENUE", items:[["Prospection","/app/prospection",Target],["Ventes / CRM","/app/ventes",BriefcaseBusiness],["Marketing","/app/marketing",Megaphone],["Communications","/app/communications",Inbox],["Réseaux sociaux","/app/social",Users]] },
  { name:"CUSTOMER", items:[["Service client","/app/service-client",Headphones],["Nova Voice","/app/voice",Mic2]] },
  { name:"COMPANY", items:[["Finance","/app/finance",CircleDollarSign],["RH","/app/rh",Users],["Opérations","/app/operations",Package],["Tâches & Projets","/app/projets",Target],["Documents","/app/documents",FileText]] },
  { name:"INTELLIGENCE", items:[["Agents IA","/app/agents",Bot],["Automatisations","/app/automatisations",Workflow],["Analytics","/app/analyses",BarChart3],["Nova Predict","/app/predict",Activity],["Connaissances","/app/connaissances",Brain],["Computer Agent","/app/computer-agent",Monitor]] },
  { name:"ECOSYSTEM", items:[["Intégrations","/app/connecteurs",Plug],["Agent Store","/app/agent-store",ShoppingBag]] },
  { name:"ADMIN", items:[["Équipe","/app/equipe",Users],["Sécurité & Contrôle","/app/securite",ShieldCheck],["Abonnement","/app/abonnement",CreditCard],["Paramètres","/app/parametres",Settings]] },
] as const;

const allItems = groups.flatMap(group => group.items.map(([label,href,Icon]) => [label,href,Icon,group.name] as const));

type Org={id:string;name:string;role:string};
export function NovaPlatformShell({ children,user,activeOrganization,organizations,enabledModules=[],navigationPriority=[],terminology }: { children: React.ReactNode;user:{name:string;email:string;image?:string|null};activeOrganization:Org;organizations:Org[];enabledModules?:string[];navigationPriority?:string[];terminology?:{contacts:string;deals:string} }) {
  const path=usePathname(); const router=useRouter();
  const [open,setOpen]=useState(false); const [collapsed,setCollapsed]=useState(false); const [palette,setPalette]=useState(false); const [query,setQuery]=useState("");
  const [orgOpen,setOrgOpen]=useState(false);const [profileOpen,setProfileOpen]=useState(false);const [switching,setSwitching]=useState(false);
  const [expanded,setExpanded]=useState<Record<string,boolean>>(()=>Object.fromEntries(groups.map(g=>[g.name,true])));
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setPalette(value=>!value)}if(event.key==="Escape")setPalette(false)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  const results=useMemo(()=>allItems.filter(item=>(item[0]+item[3]).toLowerCase().includes(query.toLowerCase())).slice(0,10),[query]);
  const current=allItems.find(item=>item[1]===path);
  const auditStatus=path==="/app/ventes"||path==="/app/prospection"?"WORKING":path==="/app/securite"||path==="/app/parametres"||path==="/app/equipe"?"PARTIAL":path==="/app/assistant"?"PARTIAL":"DEMO";
  const navigate=(href:string)=>{router.push(href==="/app/assistant"&&query?`${href}?q=${encodeURIComponent(query.replace(/^ask nova\s*:\s*/i,""))}`:href);setPalette(false);setQuery("");setOpen(false)};
  const switchOrganization=async(id:string)=>{if(id===activeOrganization.id)return setOrgOpen(false);setSwitching(true);const response=await fetch("/api/organizations/active",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:id})});if(response.ok){router.replace("/app");router.refresh()}else setSwitching(false)};
  const initials=user.name.split(" ").map(part=>part[0]).join("").slice(0,2).toUpperCase();
  const moduleHref:Record<string,string>={Dashboard:"/app",Nova:"/app/assistant",Prospection:"/app/prospection",CRM:"/app/ventes",Marketing:"/app/marketing",Communications:"/app/communications","Customer Support":"/app/service-client",Social:"/app/social",Finance:"/app/finance",Operations:"/app/operations",Tasks:"/app/projets",Documents:"/app/documents",Analytics:"/app/analyses",Calendar:"/app/calendrier",HR:"/app/rh",Automations:"/app/automatisations"};const priorityHref=navigationPriority.map(x=>moduleHref[x]).filter(Boolean);const prioritized=new Set(priorityHref);const visibleItems=priorityHref.map(href=>allItems.find(item=>item[1]===href)).filter((item):item is NonNullable<typeof item>=>Boolean(item));const otherItems=allItems.filter(item=>!prioritized.has(item[1])&&!groups.find(g=>g.name==="ADMIN")?.items.some(x=>x[1]===item[1]));const labelFor=(label:string,href:string)=>href==="/app/prospection"?(terminology?.contacts||label):href==="/app/ventes"?(terminology?.deals||label):label;
  return <div className={`nova-platform ${collapsed?"sidebar-collapsed":""}`}>
    <aside className={`platform-sidebar ${open?"open":""}`}>
      <div className="platform-logo"><Image className="platform-logo-image" src="/brand/nova-app-icon.png" width={42} height={42} priority alt="Logo NOVA"/><b>NOVA</b><small>BUSINESS OS</small><button onClick={()=>setOpen(false)} aria-label="Fermer"><X/></button></div>
      <button className="sidebar-search" onClick={()=>setPalette(true)}><Search/><span>Rechercher</span><kbd>⌘ K</kbd></button>
      <nav className="platform-group-nav"><section className="expanded"><button className="nav-group-label"><span>PRIORITY</span></button><div>{visibleItems.map(([label,href,Icon])=><Link key={href} href={href} className={path===href?"active":""} onClick={()=>setOpen(false)}><Icon/><span>{labelFor(label,href)}</span></Link>)}</div></section><section className={expanded.MORE?"expanded":""}><button className="nav-group-label" onClick={()=>setExpanded(v=>({...v,MORE:!v.MORE}))}><span>MORE / ALL MODULES</span><ChevronDown/></button><div>{otherItems.map(([label,href,Icon])=><Link key={href} href={href} className={path===href?"active":""} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></Link>)}</div></section><section className="expanded"><button className="nav-group-label"><span>ADMIN</span></button><div>{groups.find(g=>g.name==="ADMIN")!.items.map(([label,href,Icon])=><Link key={href} href={href} className={path===href?"active":""} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></Link>)}</div></section></nav>
      <div className="sidebar-live"><i><Sparkles/></i><span><b>{enabledModules.length||2} modules actifs</b><small>Configuration du workspace</small></span><em/></div>
      <button className="sidebar-collapse" onClick={()=>setCollapsed(value=>!value)} aria-label="Réduire le menu"><ChevronsLeft/><span>Réduire</span></button>
    </aside>
    <header className="platform-top"><button className="platform-menu" onClick={()=>setOpen(true)} aria-label="Menu"><Menu/></button><div className="top-breadcrumb"><span>{activeOrganization.name.toUpperCase()}</span><b>{current?.[0]||"NOVA"}</b></div><Link className={`top-audit-status ${auditStatus.toLowerCase()}`} href="/system-status">{auditStatus}</Link><div className="org-switch-wrap"><button className="top-company" onClick={()=>setOrgOpen(v=>!v)} disabled={switching}><Building2/><span>{switching?"Changement…":activeOrganization.name}</span><ChevronDown/></button>{orgOpen?<div className="org-menu"><small>ORGANISATIONS</small>{organizations.map(org=><button className={org.id===activeOrganization.id?"active":""} key={org.id} onClick={()=>void switchOrganization(org.id)}><Building2/><span><b>{org.name}</b><small>{org.role}</small></span>{org.id===activeOrganization.id?<i>✓</i>:null}</button>)}</div>:null}</div><button className="top-ask" onClick={()=>router.push("/app/assistant")}><Mic2/> Parler à Nova</button><button className="top-icon" onClick={()=>setPalette(true)} aria-label="Recherche"><Search/></button><Link className="top-icon approval" href="/app/approbations" aria-label="Validations"><ShieldCheck/></Link><button className="top-icon" aria-label="Notifications"><Bell/></button><Link className="top-icon" href="/system-status" aria-label="État système"><Activity/></Link><button className="top-icon" aria-label="Aide"><HelpCircle/></button><div className="profile-wrap"><button className="top-avatar" onClick={()=>setProfileOpen(v=>!v)} aria-label="Profil">{initials}</button>{profileOpen?<div className="profile-menu"><b>{user.name}</b><small>{user.email}</small><span>{activeOrganization.role}</span><button onClick={async()=>{await authClient.signOut();router.replace("/login");router.refresh()}}><LogOut/> Se déconnecter</button></div>:null}</div></header>
    <main className="platform-main">{children}</main>
    {open?<button className="platform-scrim" onClick={()=>setOpen(false)} aria-label="Fermer le menu"/>:null}
    {palette?<div className="command-backdrop" onClick={()=>setPalette(false)}><section className="command-palette" role="dialog" aria-modal="true" onClick={event=>event.stopPropagation()}><header><Search/><input autoFocus value={query} onChange={event=>setQuery(event.target.value)} placeholder="Rechercher une page, un client, une facture ou demander à Nova…"/><kbd>ESC</kbd></header><div className="command-results"><span>ACCÈS RAPIDE</span>{results.map(([label,href,Icon,group])=><button key={href} onClick={()=>navigate(href)}><i><Icon/></i><span><b>{label}</b><small>{group}</small></span><em>↵</em></button>)}{query?<button className="command-ask" onClick={()=>navigate("/app/assistant")}><i><Sparkles/></i><span><b>Demander à Nova</b><small>« {query} »</small></span><em>↵</em></button>:null}</div><footer><span><kbd>↑↓</kbd> naviguer</span><span><kbd>↵</kbd> ouvrir</span><span><kbd>esc</kbd> fermer</span></footer></section></div>:null}
  </div>;
}
