"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { ArrowRight, Building2, Check, LockKeyhole, Mail, ShieldCheck, Sparkles } from "lucide-react";
import { authClient } from "@/lib/auth/client";

export function AuthPage({mode}:{mode:"login"|"signup"}){const router=useRouter();const [error,setError]=useState("");const [loading,setLoading]=useState(false);async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const email=String(form.get("email"));const password=String(form.get("password"));const result=mode==="login"?await authClient.signIn.email({email,password}):await authClient.signUp.email({name:String(form.get("name")),email,password});setLoading(false);if(result.error){setError(result.error.message||"Authentification impossible");return}router.push(mode==="signup"?"/setup":"/app");router.refresh()}return <div className="auth-screen"><section className="auth-card"><div className="auth-brand"><i><Sparkles/></i><b>NOVA</b><small>BUSINESS OS</small></div><span className="auth-eyebrow"><ShieldCheck/> ACCÈS SÉCURISÉ</span><h1>{mode==="login"?"Bon retour.":"Créez votre espace Nova."}</h1><p>{mode==="login"?"Connectez-vous pour accéder à votre organisation.":"Votre compte est isolé et vos données restent liées à votre entreprise."}</p><form onSubmit={submit}>{mode==="signup"?<label>Nom complet<input name="name" required minLength={2} autoComplete="name"/></label>:null}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Mot de passe<input name="password" type="password" required minLength={10} autoComplete={mode==="login"?"current-password":"new-password"}/></label>{error?<div className="auth-error">{error}</div>:null}<button disabled={loading}>{loading?"Vérification…":mode==="login"?"Se connecter":"Créer mon compte"}<ArrowRight/></button></form><footer>{mode==="login"?<>Pas encore de compte ? <Link href="/signup">Créer un compte</Link></>:<>Déjà inscrit ? <Link href="/login">Se connecter</Link></>}<small><LockKeyhole/> Réinitialisation par email : disponible après configuration du service email.</small></footer></section></div>}

export function SetupCompany(){const router=useRouter();const [loading,setLoading]=useState(false);const [error,setError]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const body=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/organizations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setLoading(false);if(!response.ok){setError("Impossible de créer l’entreprise.");return}router.push("/onboarding");router.refresh()}return <div className="auth-screen"><section className="auth-card setup-card"><div className="auth-brand"><i><Building2/></i><b>Votre entreprise</b></div><span className="auth-eyebrow"><Check/> CONFIGURATION MINIMALE</span><h1>Créons votre organisation.</h1><p>Vous en serez propriétaire. Vous pourrez ensuite inviter votre équipe.</p><form onSubmit={submit}><label>Company name<input name="name" required minLength={2}/></label><label>Industry<input name="industry" required/></label><div><label>Country<input name="country" defaultValue="France" required/></label><label>Language<select name="language" defaultValue="fr"><option value="fr">Français</option><option value="en">English</option></select></label></div><label>Timezone<input name="timezone" defaultValue="Europe/Paris" required/></label>{error?<div className="auth-error">{error}</div>:null}<button disabled={loading}>{loading?"Création…":"Continuer la configuration"}<ArrowRight/></button></form></section></div>}

export function InviteAcceptance({token}:{token:string}){const router=useRouter();const [state,setState]=useState("");async function accept(){const response=await fetch("/api/invitations/accept",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});if(!response.ok){setState("Invitation invalide, expirée ou destinée à une autre adresse.");return}router.push("/app");router.refresh()}return <div className="auth-screen"><section className="auth-card"><div className="auth-brand"><i><Mail/></i><b>Invitation Nova</b></div><h1>Rejoindre l’organisation</h1><p>Votre session et votre adresse email seront vérifiées avant de créer le Membership.</p>{state?<div className="auth-error">{state}</div>:null}<button onClick={accept}>Accepter l’invitation <ArrowRight/></button></section></div>}
