"use client";
import Image from "next/image";import { useMemo,useState } from "react";import { useRouter } from "next/navigation";import { ArrowLeft,ArrowRight,Check,LoaderCircle,Sparkles } from "lucide-react";import type { RecommendationOutput } from "@/lib/nova/recommendations";
type Data={organization:any;profile:any;workspace:any;recommendations:RecommendationOutput};
const models=["B2B","B2C","B2B2C","Ecommerce","Subscription","Services","Marketplace","Retail","SaaS","Commission"];
const goals=["Increase sales","Find new customers","Automate repetitive tasks","Improve customer support","Reduce administrative work","Improve financial visibility","Manage employees","Improve marketing","Improve operations","Centralize company data","Save time","Reduce costs","Scale the business"];
const channels=["Email","Phone","WhatsApp","SMS","Website Chat","Instagram","Facebook","LinkedIn","TikTok"];
const processes=["Prospecting","Lead qualification","Follow-ups","Customer support","Scheduling","Quotes","Invoicing","Accounting","Administrative work","Reporting","Marketing","Content creation","Social media","Recruitment","Employee management","Document management","Data entry","Inventory","Supplier management"];
const departments=["Management","Sales","Marketing","Customer Support","Finance","HR","Operations","IT","Legal","Logistics"];
const tools:Record<string,string[]>={CRM:["Salesforce","HubSpot","Pipedrive"],Email:["Gmail","Outlook"],Calendar:["Google Calendar","Outlook Calendar"],Communication:["Slack","Microsoft Teams","WhatsApp"],Accounting:["QuickBooks","Xero","Sage","Pennylane"],Payments:["Stripe","PayPal"],Ecommerce:["Shopify","WooCommerce"],Productivity:["Notion","Google Workspace","Microsoft 365"],Storage:["Google Drive","Dropbox","OneDrive"]};
const titles=["Tell us about your company","How does your company make money?","What do you want Nova to help you achieve?","What tools does your company currently use?","How do you communicate with customers?","Which tasks take the most time?","How is your team organized?","Nova is ready to configure your workspace"];
function Choices({items,value,onChange}:{items:string[];value:string[];onChange:(v:string[])=>void}){return <div className="ob-choices">{items.map(item=><button type="button" className={value.includes(item)?"selected":""} key={item} onClick={()=>onChange(value.includes(item)?value.filter(x=>x!==item):[...value,item])}>{value.includes(item)?<Check/>:<i/>}{item}</button>)}</div>}
export function NovaOnboarding({initial}:{initial:Data}){const router=useRouter();const [step,setStep]=useState(Math.min(initial.organization.onboardingCurrentStep||1,8));const [org,setOrg]=useState(initial.organization);const [profile,setProfile]=useState(initial.profile);const [recommendations,setRecommendations]=useState(initial.recommendations);const [selected,setSelected]=useState({modules:initial.workspace.enabledModules?.length?initial.workspace.enabledModules:initial.recommendations.recommendedModules,agents:initial.workspace.desiredAgents?.length?initial.workspace.desiredAgents:initial.recommendations.recommendedAgents,automations:initial.workspace.desiredAutomations?.length?initial.workspace.desiredAutomations:initial.recommendations.recommendedAutomations,integrations:initial.workspace.desiredIntegrations?.length?initial.workspace.desiredIntegrations.map((x:any)=>x.name):initial.recommendations.recommendedIntegrations.map(x=>x.name)});const [state,setState]=useState<"idle"|"saving"|"saved">("idle");
 const currentTools=useMemo(()=>profile.currentTools||{},[profile.currentTools]);const update=(key:string,value:any)=>setProfile((p:any)=>({...p,[key]:value}));
 async function save(next=step){setState("saving");const response=await fetch("/api/onboarding",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({step:next,organization:{name:org.name,industry:org.industry,country:org.country,language:org.language,timezone:org.timezone},profile})});if(response.ok){const payload=await response.json();setRecommendations(payload.data.recommendations);setState("saved");setTimeout(()=>setState("idle"),1400);setStep(next)}else setState("idle")}
 async function finish(){setState("saving");const response=await fetch("/api/onboarding",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabledModules:selected.modules,desiredAgents:selected.agents,desiredAutomations:selected.automations,desiredIntegrations:selected.integrations.map((name:string)=>({name,status:"NOT_CONNECTED"})),dashboardPreferences:{personalized:true},industryTemplate:recommendations.industryTemplate})});if(response.ok){router.replace("/app");router.refresh()}else setState("idle")}
 const panel=useMemo(()=>{if(step===1)return <div className="ob-form"><label>Company name<input value={org.name} onChange={e=>setOrg({...org,name:e.target.value})}/></label><label>Industry<input value={org.industry} onChange={e=>setOrg({...org,industry:e.target.value})} placeholder="Restaurant, Real Estate…"/></label><label>Sub-industry<input value={profile.subIndustry||""} onChange={e=>update("subIndustry",e.target.value)}/></label><div><label>Country<input value={org.country} onChange={e=>setOrg({...org,country:e.target.value})}/></label><label>Language<input value={org.language} onChange={e=>setOrg({...org,language:e.target.value})}/></label><label>Timezone<input value={org.timezone} onChange={e=>setOrg({...org,timezone:e.target.value})}/></label></div><label>Website<input type="url" value={profile.website||""} onChange={e=>update("website",e.target.value)}/></label><div><label>Company size<select value={profile.companySize||""} onChange={e=>update("companySize",e.target.value)}><option value="">Select</option>{["Solo","2-10","11-50","51-200","201-1000","1000+"].map(x=><option key={x}>{x}</option>)}</select></label><label>Number of employees<input type="number" min="0" value={profile.employeeCount??""} onChange={e=>update("employeeCount",e.target.value?Number(e.target.value):null)}/></label></div><label>Short description<textarea rows={3} value={profile.description||""} onChange={e=>update("description",e.target.value)}/></label></div>;
 if(step===2)return <><Choices items={models} value={profile.businessModels||[]} onChange={v=>update("businessModels",v)}/><label className="ob-other">Other<input value={profile.businessModelOther||""} onChange={e=>update("businessModelOther",e.target.value)}/></label></>;
 if(step===3)return <><Choices items={goals} value={profile.goals||[]} onChange={v=>update("goals",v)}/><label className="ob-other">Other<input value={profile.goalOther||""} onChange={e=>update("goalOther",e.target.value)}/></label></>;
 if(step===4)return <div className="ob-tools">{Object.entries(tools).map(([cat,items])=><section key={cat}><b>{cat}</b><Choices items={items} value={currentTools[cat]||[]} onChange={v=>update("currentTools",{...currentTools,[cat]:v})}/></section>)}</div>;
 if(step===5)return <Choices items={channels} value={profile.communicationChannels||[]} onChange={v=>update("communicationChannels",v)}/>;
 if(step===6)return <><Choices items={processes} value={profile.timeConsumingProcesses||[]} onChange={v=>update("timeConsumingProcesses",v)}/><label className="ob-other">Describe a process you&apos;d love Nova to automate<textarea rows={4} value={profile.processToAutomate||""} onChange={e=>update("processToAutomate",e.target.value)}/></label></>;
 if(step===7)return <><Choices items={departments} value={profile.departments||[]} onChange={v=>update("departments",v)}/><div className="ob-form"><div>{[["Sales team size","salesTeamSize"],["Support team size","supportTeamSize"],["Management team size","managementTeamSize"]].map(([label,key])=><label key={key}>{label}<input type="number" min="0" value={profile[key]??""} onChange={e=>update(key,e.target.value?Number(e.target.value):null)}/></label>)}</div><label>Work mode<select value={profile.workMode||""} onChange={e=>update("workMode",e.target.value)}><option value="">Select</option><option>Office</option><option>Remote</option><option>Hybrid</option></select></label></div></>;
 return <div className="ob-recommendations">{[["Recommended Modules","modules",recommendations.recommendedModules],["Recommended AI Agents","agents",recommendations.recommendedAgents],["Recommended Automations","automations",recommendations.recommendedAutomations],["Recommended Integrations","integrations",recommendations.recommendedIntegrations.map(x=>x.name)]].map(([title,key,items]:any)=><section key={key}><header><b>{title}</b><small>{key==="modules"?"Workspace selection":"Will be configured later"}</small></header>{items.length?<Choices items={items} value={selected[key as keyof typeof selected]} onChange={v=>setSelected(s=>({...s,[key]:v}))}/>:<p>No additional recommendation for this profile.</p>}</section>)}<aside>{recommendations.reasoning.map(x=><p key={x}><Sparkles/>{x}</p>)}</aside></div>},[step,org,profile,currentTools,recommendations,selected]);
 return <main className="onboarding-shell"><header><div><Image src="/brand/nova-app-icon.png" alt="NOVA" width={46} height={46}/><span><b>NOVA</b><small>Workspace Intelligence</small></span></div><em className={state}>{state==="saving"?<LoaderCircle/>:<Check/>}{state==="saving"?"Saving…":state==="saved"?"Saved":"Saved automatically"}</em></header><div className="ob-progress"><span style={{width:`${step/8*100}%`}}/></div><section className="ob-card"><div className="ob-step">Step {step} of 8</div><h1>{titles[step-1]}</h1><p className="ob-intro">Your answers are stored securely for this organization and can be changed later.</p><div className="ob-content">{panel}</div><footer><button disabled={step===1||state==="saving"} onClick={()=>setStep(s=>s-1)}><ArrowLeft/> Back</button>{step<8?<button className="primary" disabled={state==="saving"} onClick={()=>void save(step+1)}>Continue <ArrowRight/></button>:<button className="primary build" disabled={state==="saving"} onClick={()=>void finish()}><Sparkles/> Build my Nova workspace</button>}</footer></section></main>}
