"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Activity, ArrowRight, BarChart3, Bell, Bot, Brain, BriefcaseBusiness, Calendar, CalendarClock, Camera, Check, CheckCircle2, CircleDashed, Clock3, Cloud, Code2, CreditCard, Database, FileCheck2, FileText, GitBranch, Globe2, Headphones, LockKeyhole, Mail, Megaphone, MessageCircle, MoreHorizontal, Package, Pause, Play, Plug, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Table2, Target, Trash2, TrendingUp, Users, Video, Webhook, Workflow, XCircle, Zap } from "lucide-react";

type Mission = { id: string; title: string; agent: string; schedule: string; status: "active" | "paused" };
const defaultMissions: Mission[] = [];
const connectors = [
  ["Gmail", "Emails, brouillons et suivi", Mail, "Communication"], ["Outlook", "Emails et calendrier Microsoft", CalendarClock, "Communication"], ["WhatsApp", "Messages et comptes rendus", MessageCircle, "Communication"],
  ["HubSpot", "Contacts, leads et pipeline", Users, "Ventes"], ["Salesforce", "CRM et opportunités", TrendingUp, "Ventes"], ["Notion", "Documents et base de connaissances", FileCheck2, "Connaissance"],
  ["Google Drive", "Fichiers et dossiers", Cloud, "Fichiers"], ["Slack", "Canaux et notifications", MessageCircle, "Communication"], ["Stripe", "Paiements et abonnements", CreditCard, "Finance"],
  ["Microsoft Teams", "Réunions, messages et équipes", Video, "Communication"], ["Google Calendar", "Agenda, disponibilités et événements", Calendar, "Productivité"], ["Asana", "Projets, tâches et échéances", CheckCircle2, "Productivité"],
  ["Monday.com", "Workflows et tableaux opérationnels", Table2, "Productivité"], ["Linear", "Tickets produit et cycles", Target, "Produit"], ["Jira", "Tickets, sprints et incidents", Package, "Produit"],
  ["GitHub", "Dépôts, issues et pull requests", GitBranch, "Développement"], ["Google Sheets", "Tableaux, analyses et reporting", BarChart3, "Données"], ["Airtable", "Bases métier et automatisations", Database, "Données"],
  ["Shopify", "Commandes, catalogue et clients", ShoppingBag, "Commerce"], ["WooCommerce", "Boutique, commandes et stocks", ShoppingBag, "Commerce"], ["Brevo", "Campagnes, contacts et délivrabilité", Megaphone, "Marketing"],
  ["Mailchimp", "Newsletters et audiences", Mail, "Marketing"], ["LinkedIn", "Publications et performances", BriefcaseBusiness, "Réseaux sociaux"], ["Instagram", "Contenus, commentaires et statistiques", Camera, "Réseaux sociaux"],
  ["Zendesk", "Tickets, SLA et satisfaction", Headphones, "Support"], ["Intercom", "Conversations et centre d’aide", MessageCircle, "Support"], ["Dropbox", "Documents et espaces partagés", Cloud, "Fichiers"],
  ["DocuSign", "Signatures et enveloppes", FileText, "Documents"], ["Calendly", "Rendez-vous et routage", CalendarClock, "Productivité"], ["Webhooks", "Événements entrants et sortants", Webhook, "Développeurs"],
  ["API personnalisée", "Connexion REST sécurisée sur mesure", Code2, "Développeurs"], ["Site web", "Formulaires, événements et contenu", Globe2, "Web"],
] as const;

function PageTitle({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className="product-title"><div><span>{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>{action}</div>; }
function EmptyState({ icon: Icon, title, text, action }: { icon: typeof Bot; title: string; text: string; action?: React.ReactNode }) { return <div className="product-empty"><i><Icon/></i><h2>{title}</h2><p>{text}</p>{action}</div>; }

export function DashboardPage() {
  const quickActions=[[Sparkles,"Interroger NOVA","/app/assistant"],[Plus,"Créer une mission","/app/missions"],[Workflow,"Automatiser","/app/automatisations"],[Plug,"Ajouter un outil","/app/connecteurs"]] as const;
  return <div className="product-page dashboard-page"><PageTitle eyebrow="AUJOURD’HUI" title="Vue d’ensemble" text="Votre entreprise, vos agents et les décisions importantes dans un seul espace." action={<Link className="product-primary" href="/app/assistant"><Sparkles/> Parler à NOVA</Link>}/>
    <section className="dashboard-welcome glass-panel"><div><span><i/> NOVA CORE DISPONIBLE</span><h2>Bonjour, Gamliel.</h2><p>Tout est calme. Configurez vos premiers outils pour permettre aux agents de transformer vos demandes en actions contrôlées.</p><div className="dashboard-actions">{quickActions.map(([Icon,label,href])=><Link href={href} key={label}><Icon/><span>{label}</span><ArrowRight/></Link>)}</div></div><div className="dashboard-pulse"><i/><i/><i/><Image src="/brand/nova-app-icon.png" width={110} height={110} alt="Cœur NOVA"/><span>6 agents prêts</span></div></section>
    <section className="dashboard-critical" aria-label="Informations critiques"><div><span>PRIORITÉS NOVA</span><b>3 décisions méritent votre attention</b></div><Link href="/app/approbations"><i className="critical-warn"><ShieldCheck/></i><span><b>3 validations</b><small>Actions sensibles en attente</small></span><ArrowRight/></Link><Link href="/app/predict"><i className="critical-violet"><Brain/></i><span><b>1 risque anticipé</b><small>Trésorerie à 47 jours</small></span><ArrowRight/></Link><Link href="/app/ventes"><i className="critical-green"><TrendingUp/></i><span><b>12 opportunités</b><small>Potentiel estimé 84 k€</small></span><ArrowRight/></Link></section>
    <div className="truth-metrics dashboard-metrics"><article><span className="metric-icon violet"><Bot/></span><span><strong>6</strong><small>agents disponibles</small></span><em>Prêts</em></article><article><span className="metric-icon blue"><Workflow/></span><span><strong>4</strong><small>modèles d’automatisation</small></span><em>À configurer</em></article><article><span className="metric-icon pink"><Plug/></span><span><strong>30+</strong><small>connecteurs proposés</small></span><em>Catalogue</em></article><article><span className="metric-icon green"><ShieldCheck/></span><span><strong>Actif</strong><small>contrôle humain</small></span><em>Protégé</em></article></div>
    <div className="dashboard-grid"><section className="product-card dashboard-agents"><header><div><Bot/><span><b>Équipe d’agents</b><small>Spécialistes disponibles pour vos missions</small></span></div><Link href="/app/assistant">Coordonner</Link></header><div className="agent-grid">{[["Executive","Orchestration","#7259ed"],["Ventes","Pipeline & relances","#0a84ff"],["Marketing","Contenu & acquisition","#ff375f"],["Finance","Analyse & alertes","#30d158"],["Support","Clients & qualité","#ff9f0a"],["Ops","Processus & données","#64d2ff"]].map(([name,role,color])=><article key={name}><i style={{"--agent-color":color} as React.CSSProperties}><Bot/></i><span><b>{name}</b><small>{role}</small></span><em>Prêt</em></article>)}</div></section>
      <section className="product-card dashboard-week"><header><div><BarChart3/><span><b>Cette semaine</b><small>Capacité opérationnelle</small></span></div><button aria-label="Options"><MoreHorizontal/></button></header><div className="week-chart">{[38,54,47,72,58,84,65].map((value,index)=><div key={index}><i style={{height:`${value}%`}}/><span>{["L","M","M","J","V","S","D"][index]}</span></div>)}</div><div className="week-legend"><span><i/> Actions préparées</span><b>Mode aperçu</b></div></section>
      <section className="product-card dashboard-planning"><header><div><CalendarClock/><span><b>Prochaines exécutions</b><small>Planning des automatisations</small></span></div><Link href="/app/automatisations">Gérer</Link></header>{[["08:00","Veille trésorerie","Finance"],["09:30","Qualification des leads","Ventes"],["Vendredi","Débrief exécutif","Executive"]].map(([time,title,agent])=><div className="planning-row" key={title}><time>{time}</time><span><b>{title}</b><small>{agent}</small></span><em>Modèle</em></div>)}</section>
      <section className="product-card dashboard-activity"><header><div><Activity/><span><b>Activité système</b><small>État réel de votre espace</small></span></div><Link href="/app/activite">Journal</Link></header><div className="activity-line"><i><Check/></i><span><b>Intelligence connectée</b><small>AI Gateway répond normalement</small></span><time>Maintenant</time></div><div className="activity-line"><i><ShieldCheck/></i><span><b>Approbations protégées</b><small>Validation avant action sensible</small></span><time>Actif</time></div><div className="activity-line"><i><Bell/></i><span><b>Aucune alerte critique</b><small>Le système fonctionne normalement</small></span><time>À jour</time></div></section>
    </div>
  </div>;
}

export function AgentsPage() { const agents=[["Executive","Coordonne les autres agents et synthétise vos priorités","Direction",Sparkles,"#7259ed"],["Ventes","Qualifie les opportunités et prépare les relances","Revenus",TrendingUp,"#0a84ff"],["Marketing","Prépare campagnes, contenus et analyses d’audience","Acquisition",Megaphone,"#ff375f"],["Finance","Surveille les indicateurs, factures et prévisions","Pilotage",CreditCard,"#30d158"],["Support","Classe les demandes et prépare les réponses clients","Expérience",Headphones,"#ff9f0a"],["Opérations","Documente les processus et coordonne les tâches","Exécution",Workflow,"#64d2ff"],["Data","Transforme vos données en signaux lisibles","Analyse",BarChart3,"#bf5af2"],["RH","Prépare onboarding, suivi et communications internes","Équipe",Users,"#ff6482"]] as const; return <div className="product-page"><PageTitle eyebrow="ORCHESTRATION" title="Équipe d’agents" text="Des spécialistes coordonnés par NOVA Executive, chacun limité aux outils et permissions que vous autorisez." action={<Link className="product-primary" href="/app/assistant"><Sparkles/> Coordonner l’équipe</Link>}/><div className="agents-catalog">{agents.map(([name,desc,cat,Icon,color])=><article className="glass-panel" key={name}><header><i style={{"--agent-color":color} as React.CSSProperties}><Icon/></i><em><span/> Disponible</em></header><small>{cat}</small><h2>{name}</h2><p>{desc}</p><footer><span>Mémoire partagée</span><button>Configurer <ArrowRight/></button></footer></article>)}</div></div> }

export function CalendarPage() { const events=[["Aujourd’hui","08:00","Veille de trésorerie","Finance","Préparation"],["Aujourd’hui","09:30","Qualification des nouveaux leads","Ventes","Préparation"],["Demain","10:00","Synthèse des tickets prioritaires","Support","Modèle"],["Vendredi","17:30","Rapport marketing hebdomadaire","Marketing","Modèle"],["Vendredi","18:00","Débrief exécutif WhatsApp","Executive","Approbation"]]; return <div className="product-page"><PageTitle eyebrow="PLANIFICATION" title="Calendrier opérationnel" text="Visualisez toutes les missions, automatisations et validations programmées par vos agents." action={<Link className="product-primary" href="/app/automatisations"><Plus/> Planifier</Link>}/><div className="calendar-layout"><section className="calendar-month glass-panel"><header><button>‹</button><b>Août 2026</b><button>›</button></header><div className="calendar-days">{["L","M","M","J","V","S","D"].map((day,i)=><span key={`${day}${i}`}>{day}</span>)}{Array.from({length:35},(_,i)=><button className={i===17?"today":i===18||i===21?"has-event":""} key={i}>{i<3?29+i:i-2}</button>)}</div></section><section className="calendar-agenda glass-panel"><header><div><CalendarClock/><span><b>À venir</b><small>5 exécutions proposées</small></span></div></header>{events.map(([day,time,title,agent,status])=><article key={title}><time><small>{day}</small><b>{time}</b></time><i/><span><b>{title}</b><small>{agent}</small></span><em>{status}</em></article>)}</section></div></div> }

export function AnalyticsPage() { return <div className="product-page"><PageTitle eyebrow="INTELLIGENCE" title="Analyses" text="Suivez la capacité, la fiabilité et la valeur créée par vos agents sans confondre aperçu et données réellement connectées."/><div className="analytics-banner glass-panel"><div><span>APERÇU AVANT CONNEXION</span><h2>Vos indicateurs se construiront ici.</h2><p>Connectez vos outils pour remplacer les données de démonstration par vos métriques réelles.</p></div><Link href="/app/connecteurs">Connecter mes données <ArrowRight/></Link></div><div className="analytics-grid"><article className="glass-panel"><header><b>Volume d’activité</b><em>7 jours</em></header><div className="analytics-line"><svg viewBox="0 0 500 160" aria-label="Courbe d’aperçu"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7658ed" stopOpacity=".3"/><stop offset="1" stopColor="#7658ed" stopOpacity="0"/></linearGradient></defs><path d="M0 130 C70 125 80 82 145 94 S230 132 280 72 S385 38 500 20 L500 160 L0 160Z" fill="url(#fill)"/><path d="M0 130 C70 125 80 82 145 94 S230 132 280 72 S385 38 500 20" fill="none" stroke="#7658ed" strokeWidth="4" strokeLinecap="round"/></svg></div></article><article className="glass-panel"><header><b>Répartition des agents</b><em>Aperçu</em></header><div className="analytics-donut"><i/><strong>6<small>agents</small></strong></div><div className="analytics-legend"><span><i className="v"/>Executive 28%</span><span><i className="b"/>Ventes 24%</span><span><i className="p"/>Marketing 20%</span><span><i className="g"/>Autres 28%</span></div></article></div></div> }

export function MissionsPage() {
  const [missions,setMissions]=useState<Mission[]>(()=>{if(typeof window==="undefined")return defaultMissions;const value=localStorage.getItem("nova-missions-v1");if(value)try{return JSON.parse(value) as Mission[]}catch{}return defaultMissions}); const [creating,setCreating]=useState(false); const [title,setTitle]=useState("");
  const persist=(next:Mission[])=>{setMissions(next);localStorage.setItem("nova-missions-v1",JSON.stringify(next))};
  const create=()=>{if(!title.trim())return;persist([...missions,{id:crypto.randomUUID(),title:title.trim(),agent:"Executive",schedule:"Manuel",status:"active"}]);setTitle("");setCreating(false)};
  return <div className="product-page"><PageTitle eyebrow="EXÉCUTION" title="Missions" text="Créez, planifiez et suivez chaque objectif confié à NOVA." action={<button className="product-primary" onClick={()=>setCreating(true)}><Plus/> Nouvelle mission</button>}/>{creating?<div className="creation-card"><div><span>NOUVELLE MISSION</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Préparer le bilan commercial du mois"/></div><select aria-label="Agent"><option>Executive</option></select><select aria-label="Fréquence"><option>Exécution manuelle</option></select><button onClick={create}>Créer</button><button className="icon-button" onClick={()=>setCreating(false)}><XCircle/></button></div>:null}
    {missions.length===0?<EmptyState icon={Target} title="Aucune mission planifiée" text="Une mission rassemble un objectif, un agent responsable, une fréquence et des règles d’approbation." action={<button className="product-primary" onClick={()=>setCreating(true)}><Plus/> Créer la première mission</button>}/>:<div className="mission-table"><header><span>MISSION</span><span>AGENT</span><span>PLANIFICATION</span><span>ÉTAT</span><span/></header>{missions.map(m=><div key={m.id}><span><i><Target/></i><b>{m.title}</b></span><span>{m.agent}</span><span>{m.schedule}</span><span className={m.status}><i/>{m.status==="active"?"Active":"En pause"}</span><span><button onClick={()=>persist(missions.map(x=>x.id===m.id?{...x,status:x.status==="active"?"paused":"active"}:x))}>{m.status==="active"?<Pause/>:<Play/>}</button><button onClick={()=>persist(missions.filter(x=>x.id!==m.id))}><Trash2/></button></span></div>)}</div>}
  </div>;
}

export function AutomationsPage() { const recipes=[["Compte rendu exécutif hebdomadaire","Executive","Chaque vendredi à 18:00"],["Qualification et relance des nouveaux leads","Ventes","À chaque nouveau contact"],["Alerte de trésorerie prévisionnelle","Finance","Chaque matin à 08:00"],["Synthèse des demandes clients","Support","Toutes les 4 heures"]]; return <div className="product-page"><PageTitle eyebrow="AUTOMATISATION" title="Automatisations" text="Construisez des scénarios déclenchés par un événement, contrôlés par vos règles et confirmés par les services connectés." action={<button className="product-primary"><Plus/> Créer un scénario</button>}/><div className="automation-builder"><div><span>QUAND</span><i><Zap/></i><b>Un événement survient</b><small>Nouveau lead, date, email, seuil…</small></div><ArrowRight/><div><span>NOVA</span><i><Sparkles/></i><b>Comprend et décide</b><small>Analyse, règles et contexte métier</small></div><ArrowRight/><div><span>ALORS</span><i><Workflow/></i><b>Prépare ou exécute</b><small>Selon permissions et approbations</small></div></div><div className="section-label"><span>MODÈLES PRÊTS À CONFIGURER</span><b>{recipes.length} scénarios</b></div><div className="recipe-grid">{recipes.map(([name,agent,trigger])=><article key={name}><header><i><Workflow/></i><button><MoreHorizontal/></button></header><span>{agent}</span><h2>{name}</h2><p><Clock3/> {trigger}</p><footer><em>Connecteurs requis</em><Link href="/app/connecteurs">Configurer <ArrowRight/></Link></footer></article>)}</div></div>; }

export function ApprovalsPage() { return <div className="product-page"><PageTitle eyebrow="CONTRÔLE HUMAIN" title="Approbations" text="Aucun email, paiement, publication ou modification sensible ne part sans la validation prévue."/><div className="approval-tabs"><button className="active">En attente <b>0</b></button><button>Approuvées</button><button>Refusées</button><button>Règles</button></div><EmptyState icon={ShieldCheck} title="Aucune décision en attente" text="Les actions sensibles préparées par les agents apparaîtront ici avec leur destination, leur contenu, leur impact et leur réversibilité."/><div className="approval-policy"><LockKeyhole/><div><b>Protection active par défaut</b><p>Communications externes, publications, paiements, suppressions et changements de données exigent une validation.</p></div><button>Gérer les règles</button></div></div>; }

export function ConnectorsPage() { const [query,setQuery]=useState(""); const visible=connectors.filter(([name,, ,cat])=>(name+cat).toLowerCase().includes(query.toLowerCase())); return <div className="product-page"><PageTitle eyebrow="ÉCOSYSTÈME" title="Connecteurs & plugins" text="Reliez les services que NOVA est autorisée à consulter ou piloter. Chaque connexion utilise son propre consentement OAuth."/><div className="connector-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un outil ou une catégorie"/></label><span><ShieldCheck/> 0 service connecté</span></div><div className="connector-grid">{visible.map(([name,desc,Icon,cat])=><article key={name}><header><i><Icon/></i><span>{cat}</span></header><h2>{name}</h2><p>{desc}</p><button>Connecter <ArrowRight/></button></article>)}</div><div className="connector-request"><Plug/><div><b>Votre outil n’est pas listé ?</b><p>NOVA pourra accueillir des connecteurs OAuth, API et webhooks personnalisés.</p></div><button>Demander un connecteur</button></div></div>; }

export function MemoryPage() { const initial=()=>{if(typeof window==="undefined")return {company:"",sector:"",rules:""};try{return JSON.parse(localStorage.getItem("nova-memory-v1")||"{}") as {company?:string;sector?:string;rules?:string}}catch{return {company:"",sector:"",rules:""}}};const [memory,setMemory]=useState(()=>initial());const save=()=>localStorage.setItem("nova-memory-v1",JSON.stringify(memory));return <div className="product-page"><PageTitle eyebrow="CONTEXTE" title="Mémoire d’entreprise" text="Les informations que NOVA doit connaître pour raisonner selon votre activité, vos règles et vos priorités." action={<button className="product-primary" onClick={save}><Check/> Enregistrer</button>}/><div className="memory-layout"><section className="memory-form"><label>Nom de l’entreprise<input value={memory.company||""} onChange={e=>setMemory({...memory,company:e.target.value})} placeholder="Votre entreprise"/></label><label>Secteur d’activité<input value={memory.sector||""} onChange={e=>setMemory({...memory,sector:e.target.value})} placeholder="Ex. restauration, conseil, e-commerce"/></label><label>Règles permanentes<textarea value={memory.rules||""} onChange={e=>setMemory({...memory,rules:e.target.value})} rows={9} placeholder="Ex. Toujours demander mon accord avant un envoi client…"/></label></section><aside><Brain/><h2>Mémoire locale active</h2><p>Ces informations restent pour l’instant dans ce navigateur. La synchronisation cloud nécessitera une base de données et une authentification.</p><ul><li><CheckCircle2/> Contexte métier</li><li><CheckCircle2/> Préférences locales</li><li><CircleDashed/> Mémoire cloud</li><li><CircleDashed/> Partage d’équipe</li></ul></aside></div></div>;}

export function ActivityPage() { return <div className="product-page"><PageTitle eyebrow="TRAÇABILITÉ" title="Journal d’activité" text="Une chronologie destinée à distinguer les analyses, préparations, validations et exécutions confirmées."/><div className="activity-feed"><div className="activity-date">AUJOURD’HUI</div>{[[CheckCircle2,"Connexion IA vérifiée","Une réponse réelle a été reçue via AI Gateway.","Exécuté"],[ShieldCheck,"Règles de validation chargées","Les actions externes sensibles restent bloquées avant accord.","Sécurité"],[Database,"Mémoire locale disponible","Le contexte peut être enregistré dans ce navigateur.","Local"]].map(([Icon,title,text,status],i)=><article key={title as string}><i><Icon/></i><div><span>{status as string}</span><h2>{title as string}</h2><p>{text as string}</p></div><time>{i===0?"Maintenant":"Configuration"}</time></article>)}</div></div>; }

export function SettingsPage() { return <div className="product-page"><PageTitle eyebrow="CONFIGURATION" title="Paramètres" text="Modèles, sécurité, limites et comportement de votre espace NOVA."/><div className="settings-grid"><section><header><Sparkles/><div><b>Intelligence artificielle</b><small>Modèle et consommation</small></div></header><div className="setting-row"><span><b>Modèle actif</b><small>Gratuit, aucune facturation par token</small></span><em>Laguna S 2.1 Free</em></div><div className="setting-row"><span><b>Mode supérieur</b><small>Nécessite des crédits payants volontaires</small></span><em>Désactivé</em></div></section><section><header><ShieldCheck/><div><b>Sécurité</b><small>Permissions et contrôle</small></div></header><div className="setting-row"><span><b>Approbations sensibles</b><small>Envoi, paiement, publication, suppression</small></span><em className="green">Toujours actives</em></div><div className="setting-row"><span><b>Connecteurs</b><small>Autorisations service par service</small></span><em>0 autorisé</em></div></section><section><header><Database/><div><b>Données</b><small>Stockage et conservation</small></div></header><div className="setting-row"><span><b>Mémoire</b><small>Stockée uniquement sur cet appareil</small></span><em>Locale</em></div><div className="setting-row"><span><b>Base cloud</b><small>Requise pour les équipes et l’historique durable</small></span><em>À configurer</em></div></section></div></div>; }
