"use client";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { Archive, ChevronLeft, Database, Menu, MessageSquare, Plus, Send, Sparkles, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Conversation, ConversationContent, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputBody, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";

type ConversationRow={id:string;title:string;updatedAt:string};
const prompts:Record<string,string[]>={
  real_estate:["Which leads need attention?","Summarize my pipeline.","What should I follow up on?"],
  restaurant:["What should I focus on today?","Summarize recent customer activity.","What does Nova know about my business?"],
  ecommerce:["Summarize my customer base.","Analyze my pipeline.","What needs my attention today?"],
  generic:["Summarize my business.","What needs my attention?","Analyze my pipeline."],
};
const toolNames:Record<string,string>={company_getProfile:"Reading company profile",crm_contacts_summary:"Consulting CRM",crm_contacts_search:"Searching contacts",crm_contact_get:"Reading contact",crm_pipeline_summary:"Analyzing pipeline",crm_deals_list:"Reading opportunities",crm_deal_get:"Reading opportunity",workspace_getContext:"Reading workspace context",business_getBrief:"Building business brief"};

export function NovaAiChat({initialPrompt,template}:{initialPrompt:string;template:string}){
  const [conversations,setConversations]=useState<ConversationRow[]>([]),[active,setActive]=useState<string>(),[initialMessages,setInitialMessages]=useState<UIMessage[]>([]),[pending,setPending]=useState(initialPrompt),[sidebar,setSidebar]=useState(false),[loading,setLoading]=useState(true);
  const refresh=useCallback(async()=>{const r=await fetch("/api/nova/conversations",{cache:"no-store"});if(r.ok)setConversations((await r.json()).data)},[]);
  const create=useCallback(async(prompt="")=>{const r=await fetch("/api/nova/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!r.ok)return;const c=(await r.json()).data;setInitialMessages([]);setActive(c.id);setPending(prompt);setSidebar(false);await refresh()},[refresh]);
  useEffect(()=>{void (async()=>{await refresh();setLoading(false)})()},[refresh]);
  useEffect(()=>{if(loading||active)return;const timer=window.setTimeout(()=>{if(initialPrompt)void create(initialPrompt);else if(conversations[0])void open(conversations[0].id)},0);return()=>window.clearTimeout(timer)},[loading,active,conversations,initialPrompt,create]);
  async function open(id:string){const r=await fetch(`/api/nova/conversations/${id}`,{cache:"no-store"});if(!r.ok)return;const data=(await r.json()).data;setInitialMessages(data.messages);setActive(id);setPending("");setSidebar(false)}
  async function archive(id:string){await fetch(`/api/nova/conversations/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({archived:true})});if(active===id){setActive(undefined);setInitialMessages([])}await refresh()}
  async function remove(id:string){if(!confirm("Delete this conversation?"))return;await fetch(`/api/nova/conversations/${id}`,{method:"DELETE"});if(active===id){setActive(undefined);setInitialMessages([])}await refresh()}
  const suggested=prompts[template]||prompts.generic;
  return <div className="nova-ai-shell"><button className="nova-ai-mobile-toggle" onClick={()=>setSidebar(true)}><Menu/> Conversations</button><aside className={sidebar?"open":""}><header><span><i><Sparkles/></i><b>Nova</b></span><button onClick={()=>create()}><Plus/> New Chat</button></header><div className="nova-conversation-list">{loading?<small>Loading conversations…</small>:conversations.length?conversations.map(c=><article className={active===c.id?"active":""} key={c.id}><button onClick={()=>open(c.id)}><MessageSquare/><span><b>{c.title}</b><small>{new Date(c.updatedAt).toLocaleDateString()}</small></span></button><div><button title="Archive" onClick={()=>archive(c.id)}><Archive/></button><button title="Delete" onClick={()=>remove(c.id)}><Trash2/></button></div></article>):<div className="nova-ai-empty-list"><MessageSquare/><p>Your conversations will appear here.</p></div>}</div><footer><Database/><span><b>Private workspace</b><small>PostgreSQL · active organization only</small></span></footer><button className="nova-ai-close" onClick={()=>setSidebar(false)}><X/></button></aside><main>{active?<ChatPane key={active} id={active} initialMessages={initialMessages} pending={pending} suggestions={suggested} onSent={()=>{setPending("");void refresh()}}/>:<section className="nova-ai-welcome"><i><Sparkles/></i><h1>Ask Nova about your company.</h1><p>Nova reads only the verified business data available to you.</p><button onClick={()=>create()}><Plus/> Start a conversation</button></section>}</main>{sidebar?<div className="nova-ai-backdrop" onClick={()=>setSidebar(false)}/>:null}</div>
}

function ChatPane({id,initialMessages,pending,suggestions,onSent}:{id:string;initialMessages:UIMessage[];pending:string;suggestions:string[];onSent:()=>void}){
  const transport=useMemo(()=>new DefaultChatTransport({api:"/api/nova/chat",body:{conversationId:id}}),[id]);
  const {messages,sendMessage,status,stop,error}=useChat({id,messages:initialMessages,transport,onFinish:onSent});const sent=useRef(false),hasMessages=messages.length>0;
  useEffect(()=>{if(pending&&!sent.current){sent.current=true;void sendMessage({text:pending})}},[pending,sendMessage]);
  async function submit(text:string){const value=text.trim();if(value)await sendMessage({text:value})}
  return <section className="nova-ai-chat"><header><div><button className="nova-back-mobile"><ChevronLeft/></button><span>NOVA AI CORE</span><b>{status==="streaming"||status==="submitted"?"Reading your workspace…":"Ready · Read-only"}</b></div><em><i/> Live company context</em></header><Conversation className="nova-ai-scroll"><ConversationContent>{!hasMessages?<div className="nova-ai-hero"><div className="nova-ai-orb"><Sparkles/></div><h1>What would you like to understand?</h1><p>Ask about your company profile, contacts, opportunities or priorities.</p><div>{suggestions.map(p=><button key={p} onClick={()=>submit(p)}>{p}<Send/></button>)}</div></div>:messages.map(message=><Message from={message.role} key={message.id}><MessageContent>{message.parts.map((part,index)=>{if(part.type==="text")return <MessageResponse key={index}>{part.text}</MessageResponse>;if(part.type.startsWith("tool-")||part.type==="dynamic-tool"){const name=part.type==="dynamic-tool"?(part as any).toolName:part.type.slice(5),output=(part as any).output;return <div className="nova-tool-card" key={index}><i><Database/></i><span><b>{toolNames[name]||"Reading verified business data"}</b><small>{(part as any).state==="output-available"?(output?.source||output?._nova?.name||"Verified source"):"Secure query in progress"}</small></span><em>READ ONLY</em></div>}return null})}</MessageContent></Message>)}{error?<div className="nova-ai-error">Nova couldn’t complete this response. No business data was changed. Please retry.</div>:null}</ConversationContent><ConversationScrollButton/></Conversation><div className="nova-ai-composer"><PromptInput onSubmit={({text})=>submit(text)}><PromptInputBody><PromptInputTextarea placeholder="Ask Nova about your business…"/></PromptInputBody><PromptInputFooter><span><Sparkles/> Verified workspace data · Read-only</span><PromptInputSubmit status={status} onStop={stop}><Send/></PromptInputSubmit></PromptInputFooter></PromptInput><p>Nova can analyze and recommend, but cannot modify or send anything in this release.</p></div></section>
}
