"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bot, Brain, CalendarClock, Check, ChevronRight, FileText, Globe2, Megaphone, MessageCircle, Monitor, MoreHorizontal, Package, Pause, Phone, Plus, Search, ShieldCheck, Sparkles, Star, TrendingUp, Users } from "lucide-react";
import { LiveCrm, LiveProspecting } from "@/components/nova-crm-live";

type ModuleConfig={title:string;eyebrow:string;description:string;tabs:string[];kind:string;metrics:[string,string,string][]};
export const moduleConfigs:Record<string,ModuleConfig>={
  "nova-manager":{title:"Nova Manager",eyebrow:"DIRECTION AUGMENTÉE",description:"L’IA exécutive qui transforme les objectifs du dirigeant en plans coordonnés pour toute l’entreprise.",tabs:["Vue Manager","Objectifs","Équipe IA","Missions","Plans","Décisions","Résultats","KPI","Budget","Rapports","Activité"],kind:"manager",metrics:[["7","agents coordonnés","Tous actifs"],["24","missions cette semaine","+18 %"],["82 %","objectifs en bonne voie","4 à surveiller"],["18 420 €","valeur estimée créée","Ce mois"]]},
  autopilot:{title:"Autopilot",eyebrow:"AUTONOMIE CONTRÔLÉE",description:"Choisissez jusqu’où NOVA peut agir seule et gardez un arrêt général toujours accessible.",tabs:["Mode actuel","Autorisations","Limites financières","Actions","Validation humaine","Horaires","Budget","Agents","Historique"],kind:"autopilot",metrics:[["Assisté","mode actuel","Sûr"],["34","actions aujourd’hui","12 automatiques"],["3","validations requises","À traiter"],["0","incident","30 derniers jours"]]},
  prospection:{title:"Prospection",eyebrow:"ACQUISITION",description:"Trouvez, enrichissez et qualifiez automatiquement les entreprises ayant le meilleur potentiel commercial.",tabs:["Recherche","Base prospects","Enrichissement","Lead Scoring","Listes","Import","Intent Signals","Recommandés"],kind:"prospecting",metrics:[["2 847","prospects","+184 cette semaine"],["76/100","score moyen","Qualifié"],["127","signaux d’intention","À exploiter"],["14","RDV obtenus","5,7 % conversion"]]},
  ventes:{title:"Ventes / CRM",eyebrow:"REVENUE",description:"Unifiez les contacts, les opportunités et toutes les interactions commerciales dans un pipeline intelligent.",tabs:["Dashboard","Leads","Contacts","Entreprises","Opportunités","Pipeline","Rendez-vous","Devis","Contrats","Relances","Objectifs","Prévisions","Analytics","Activité"],kind:"crm",metrics:[["184 600 €","pipeline pondéré","+14 %"],["42","opportunités","8 prioritaires"],["18","rendez-vous","Cette semaine"],["31 %","taux de closing","+4,2 pts"]]},
  communications:{title:"Communications",eyebrow:"UNIFIED INBOX",description:"Email, WhatsApp, SMS, téléphone, chat et réseaux sociaux réunis dans un seul centre de communication.",tabs:["Inbox","Email","WhatsApp","SMS","Téléphone","Chat","Réseaux sociaux","Modèles","Signatures","Campagnes","Contacts","Historique"],kind:"communications",metrics:[["38","non lus","6 prioritaires"],["4 min","temps de réponse","−32 %"],["94 %","traités aujourd’hui","NOVA + équipe"],["7","canaux connectés","Tous disponibles"]]},
  marketing:{title:"Marketing",eyebrow:"GROWTH STUDIO",description:"Planifiez, créez et optimisez l’ensemble des campagnes depuis une vue marketing unifiée.",tabs:["Dashboard","Campagnes","Email Marketing","SMS","WhatsApp","Social Media","Publicités","Landing Pages","Formulaires","Audiences","Contenu","Calendrier","SEO","A/B Tests","Attribution","Budget","Analytics"],kind:"marketing",metrics:[["486 k","impressions","+22 %"],["12 840","leads générés","+18 %"],["4,8x","ROAS moyen","Excellent"],["34 200 €","budget utilisé","68 %"]]},
  social:{title:"Réseaux sociaux",eyebrow:"SOCIAL COMMAND",description:"Créez, programmez et analysez toutes les prises de parole sociales de vos marques.",tabs:["Dashboard","Calendrier","Publications","Créer","Brouillons","Instagram","TikTok","LinkedIn","Facebook","X","YouTube","Commentaires","Messages","Mentions","Analytics","Veille"],kind:"social",metrics:[["248 k","abonnés","+4,7 %"],["6,8 %","engagement","Au-dessus du secteur"],["42","publications planifiées","3 marques"],["184","mentions","12 à traiter"]]},
  "service-client":{title:"Service client",eyebrow:"CUSTOMER EXPERIENCE",description:"Résolvez les demandes sur tous les canaux et détectez les clients qui nécessitent une attention humaine.",tabs:["Dashboard SAV","Inbox omnicanale","Tickets","Clients","Conversations","Appels SAV","Knowledge Base","FAQ","Réponses automatiques","Satisfaction","Litiges","Remboursements","Customer Success","Clients à risque"],kind:"support",metrics:[["84","demandes traitées","Aujourd’hui"],["76","résolues par NOVA","90,4 %"],["94 %","satisfaction","+3 pts"],["8","clients à risque","À contacter"]]},
  voice:{title:"Nova Voice",eyebrow:"TÉLÉPHONIE IA",description:"Déployez des agents vocaux pour prospecter, accueillir, qualifier, réserver et assister vos clients.",tabs:["Dashboard appels","Appels en direct","Historique","Numéros","Entrants","Campagnes sortantes","Scripts","Voix","Transferts","Analytics Voice"],kind:"voice",metrics:[["247","appels aujourd’hui","+18 %"],["82 %","taux de décroché","Excellent"],["14","RDV obtenus","5,7 % conversion"],["2:48","durée moyenne","−12 sec"]]},
  finance:{title:"Finance",eyebrow:"CFO CENTER",description:"Pilotez chiffre d’affaires, trésorerie, marges, budgets et échéances depuis une vision financière consolidée.",tabs:["Vue financière","Chiffre d’affaires","Trésorerie","Factures clients","Factures fournisseurs","Paiements","Dépenses","Abonnements","Impayés","Relances","Fournisseurs","Comptabilité","Rapprochement","Prévisions","Budgets","Marges","Taxes","Documents","Analytics"],kind:"finance",metrics:[["428 600 €","chiffre d’affaires","+12,4 %"],["184 200 €","trésorerie","92 jours"],["71,8 %","marge brute","+2,1 pts"],["18 420 €","à encaisser","6 factures"]]},
  rh:{title:"Ressources humaines",eyebrow:"PEOPLE",description:"Centralisez les collaborateurs, recrutements, plannings, congés, formations et performances.",tabs:["Dashboard RH","Employés","Recrutement","Candidatures","Entretiens","Onboarding","Planning","Présences","Absences","Congés","Documents","Paie","Notes de frais","Formations","Performances","Organigramme","Assistant RH"],kind:"hr",metrics:[["48","collaborateurs","3 équipes"],["12","candidatures","5 qualifiées"],["96 %","présence","Cette semaine"],["4","onboardings","En cours"]]},
  operations:{title:"Opérations",eyebrow:"OPERATING SYSTEM",description:"Supervisez commandes, stocks, achats, logistique, qualité et incidents opérationnels.",tabs:["Dashboard","Commandes","Stocks","Produits","Services","Fournisseurs","Achats","Approvisionnement","Logistique","Livraisons","Incidents","Qualité","Processus","Prévisions","Alertes"],kind:"operations",metrics:[["1 284","commandes","+8 %"],["96,7 %","livrées à temps","Excellent"],["14","stocks faibles","À commander"],["3","incidents ouverts","1 prioritaire"]]},
  projets:{title:"Tâches & Projets",eyebrow:"EXECUTION",description:"Organisez le travail des humains et des agents IA dans une même vue opérationnelle.",tabs:["Mes tâches","Tâches Nova","Tâches équipe","Projets","Kanban","Calendrier","Timeline","Priorités","Automatisations","Activité"],kind:"projects",metrics:[["42","tâches actives","18 NOVA"],["87 %","à l’heure","+6 pts"],["8","projets","2 prioritaires"],["184 h","temps économisé","Ce mois"]]},
  predict:{title:"Nova Predict",eyebrow:"INTELLIGENCE PRÉDICTIVE",description:"Anticipez les risques, opportunités et anomalies avant qu’ils n’affectent l’entreprise.",tabs:["Prévisions","Opportunités","Risques","Anomalies","Trésorerie","Ventes","Churn","Stocks","Marketing","Recommandations"],kind:"predict",metrics:[["12","opportunités","Potentiel 84 k€"],["4","risques élevés","À traiter"],["7","anomalies détectées","3 résolues"],["91 %","précision moyenne","30 jours"]]},
  "computer-agent":{title:"Computer Agent",eyebrow:"DIGITAL OPERATOR",description:"Regardez NOVA utiliser un navigateur et vos applications pour réaliser les tâches autorisées.",tabs:["Mes ordinateurs","Sessions","Tâches navigateur","Applications","Historique","Captures","Actions","Permissions"],kind:"computer",metrics:[["2","sessions actives","Surveillées"],["18","tâches terminées","Aujourd’hui"],["4h 26","temps économisé","Cette semaine"],["0","action bloquée","Conforme"]]},
  "agent-store":{title:"Agent Store",eyebrow:"MARKETPLACE",description:"Ajoutez en quelques secondes des employés IA préconfigurés pour chaque fonction de l’entreprise.",tabs:["Découvrir","Vente","Prospection","Support","Marketing","Finance","RH","Ecommerce","Administration","Opérations","Data","Mes agents"],kind:"store",metrics:[["128","agents disponibles","12 catégories"],["24","certifiés NOVA","Recommandés"],["8","installés","7 actifs"],["4,8/5","note moyenne","2 400 avis"]]},
  connaissances:{title:"Connaissances",eyebrow:"ENTERPRISE BRAIN",description:"La mémoire centrale qui relie les produits, clients, procédures et sources de toute l’entreprise.",tabs:["Knowledge Base","Mémoire Nova","Entreprise","Produits","Services","Clients","Fournisseurs","Procédures","FAQ","Documents","Sites web","Sources connectées","Règles internes","Instructions Nova","Historique"],kind:"knowledge",metrics:[["24 860","éléments indexés","À jour"],["18","sources connectées","Synchronisées"],["96 %","couverture","+4 pts"],["7","contenus obsolètes","À réviser"]]},
  abonnement:{title:"Abonnement & utilisation",eyebrow:"ADMINISTRATION",description:"Suivez l’offre NOVA, les crédits, les minutes Voice, les agents actifs et le stockage.",tabs:["Mon abonnement","Utilisation","Crédits IA","Minutes Voice","Agents actifs","Stockage","Factures Nova","Moyens de paiement","Changer d’offre","Historique"],kind:"subscription",metrics:[["72 %","crédits IA","18 jours restants"],["43 %","minutes Voice","4 260 min"],["61 %","automatisations","12 480 runs"],["28 %","stockage","28 Go / 100 Go"]]},
};

const MetricCards=({items}:{items:[string,string,string][]})=><div className="em-metrics">{items.map(([value,label,note],index)=><article className="glass-panel" key={label}><i className={`tone-${index}`}><BarChart3/></i><span><strong>{value}</strong><small>{label}</small></span><em>{note}</em></article>)}</div>;
const Sparkline=()=> <svg className="em-sparkline" viewBox="0 0 600 180" aria-label="Évolution sur 30 jours"><defs><linearGradient id="emfill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7658ed" stopOpacity=".28"/><stop offset="1" stopColor="#7658ed" stopOpacity="0"/></linearGradient></defs><path d="M0 142 C45 125 75 140 115 112 S180 88 220 106 S285 137 320 78 S385 50 420 72 S495 54 600 24 L600 180 L0 180Z" fill="url(#emfill)"/><path d="M0 142 C45 125 75 140 115 112 S180 88 220 106 S285 137 320 78 S385 50 420 72 S495 54 600 24" fill="none" stroke="#7658ed" strokeWidth="4" strokeLinecap="round"/></svg>;

function VoiceView(){return <div className="em-grid voice-view"><section className="em-card glass-panel span-2"><div className="em-card-head"><span><i className="live"/> APPELS EN DIRECT</span><button>Voir le centre d’appels <ArrowRight/></button></div>{[["Nova Commercial","Jean Dupont","03:42","Qualification en cours","+33 6 12 84 56 90"],["Nova Standardiste","Cabinet Morel","01:18","Prise de rendez-vous","+33 4 93 22 18 04"],["Nova Support","Claire Martin","06:09","Diagnostic commande #9841","+33 7 45 11 02 38"]].map(([agent,name,time,status,number])=><article className="live-call" key={name}><i><Phone/></i><span><b>{agent}</b><small>{name} · {number}</small></span><div className="call-wave">{Array.from({length:14},(_,i)=><i key={i} style={{height:`${7+(i*7)%20}px`}}/>)}</div><em>{status}</em><strong>{time}</strong><button><Monitor/></button></article>)}</section><section className="em-card glass-panel"><div className="em-card-head"><span>PERFORMANCE 7 JOURS</span><em>+18,4 %</em></div><Sparkline/><div className="chart-caption"><b>1 482 appels</b><span>82 % décrochés</span></div></section><section className="em-card glass-panel"><div className="em-card-head"><span>CAMPAGNES ACTIVES</span><button><Plus/></button></div>{[["Réactivation Q3","684 / 1 200","57%"],["Prospects Immobilier","248 / 500","49%"],["Relance devis","92 / 120","77%"]].map(([name,count,progress])=><div className="campaign-row" key={name}><span><b>{name}</b><small>{count} appels</small></span><i><b style={{width:progress}}/></i><em>{progress}</em></div>)}</section></div>}

function DemoCRMView(){
  const columns=[["Nouveau","42","#6c77ef"],["Contacté","31","#5ea4ef"],["Qualifié","18","#9b68e8"],["RDV","12","#e166b1"],["Proposition","8","#eb8a57"],["Gagné","6","#39b879"]] as const;
  const [cards,setCards]=useState(()=>columns.flatMap((_,column)=>
    Array.from({length:column > 3 ? 2 : 3},(_,index)=>({
      id:`${column}-${index}`,
      column,
      company:["Maison Verne","Atelier Rivoli","Studio Marais","Groupe Néo"][(column+index)%4],
      title:["Refonte acquisition","Déploiement NOVA","Support Enterprise","Automatisation CRM"][index%4],
      value:["18 500 €","9 800 €","24 000 €"][index%3],
      owner:["GN","SM","JL"][index%3],
      days:column+index+2,
    }))
  ));
  const [dragging,setDragging]=useState<string|null>(null); const [over,setOver]=useState<number|null>(null);
  const drop=(column:number)=>{if(!dragging)return;setCards(items=>items.map(card=>card.id===dragging?{...card,column}:card));setDragging(null);setOver(null)};
  return <div className="crm-board">{columns.map(([name,count,color],column)=><section className={over===column?"drop-ready":""} onDragOver={event=>{event.preventDefault();setOver(column)}} onDragLeave={()=>setOver(value=>value===column?null:value)} onDrop={()=>drop(column)} key={name}><header><i style={{background:color}}/><b>{name}</b><em>{count}</em></header>{cards.filter(card=>card.column===column).map(card=><article draggable onDragStart={()=>setDragging(card.id)} onDragEnd={()=>{setDragging(null);setOver(null)}} className={`glass-panel ${dragging===card.id?"is-dragging":""}`} key={card.id}><span>{card.company}</span><h3>{card.title}</h3><b>{card.value}</b><footer><i>{card.owner}</i><time>{card.days} j</time></footer></article>)}<div className="crm-drop-indicator"><Plus/> Déposer ici</div></section>)}</div>
}

function GenericTable({kind}:{kind:string}){const maps:Record<string,string[][]>={prospecting:[["Maison Aster","Sophie Martin","CEO","94","Intention forte"],["Groupe Belvédère","Julien Morel","Directeur commercial","88","Site visité 4×"],["Studio Éclat","Léa Robert","Fondatrice","82","Recrutement Sales"],["Atelier Rivoli","Marc Petit","COO","79","Nouveau financement"]],support:[["#9841","Claire Martin","Commande non reçue","Urgent","Nova Support"],["#9838","Thomas Leroy","Demande de remboursement","En cours","Sophie"],["#9834","Camille Roux","Erreur de facturation","Résolu","Nova Finance"],["#9829","Paul Bernard","Modification abonnement","En attente","Nova Support"]],operations:[["CMD-2841","Maison Aster","12 produits","Expédiée","Demain"],["CMD-2840","Studio Marais","4 produits","Préparation","Aujourd’hui"],["CMD-2839","Groupe Néo","28 produits","Livrée","12 août"],["CMD-2838","Atelier Rivoli","7 produits","Incident","Retard 2j"]],hr:[["Sophie Martin","Marketing Manager","Marketing","Présente","94 %"],["Julien Morel","Account Executive","Ventes","En RDV","108 %"],["Léa Robert","Customer Success","Support","Télétravail","97 %"],["Marc Petit","Operations Lead","Opérations","Présent","91 %"]]};const rows=maps[kind]||maps.prospecting;return <section className="em-card glass-panel em-table"><div className="em-card-head"><span>{kind==="support"?"TICKETS PRIORITAIRES":kind==="hr"?"ÉQUIPE":kind==="operations"?"COMMANDES RÉCENTES":"PROSPECTS RECOMMANDÉS"}</span><div><button><Search/></button><button><Plus/> Ajouter</button></div></div><div className="em-table-labels">{["NOM / RÉFÉRENCE","CONTACT / OBJET","SEGMENT","STATUT","PROCHAINE ACTION"].map(x=><span key={x}>{x}</span>)}</div>{rows.map(row=><article key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===3?"status":""}>{i===0?<b>{cell}</b>:cell}</span>)}<button><MoreHorizontal/></button></article>)}</section>}

function MarketingView({social=false}:{social?:boolean}){return <div className="em-grid"><section className="em-card glass-panel span-2"><div className="em-card-head"><span>{social?"CALENDRIER DE PUBLICATION":"PERFORMANCE DES CAMPAGNES"}</span><button>30 derniers jours <ChevronRight/></button></div><Sparkline/><div className="chart-caption"><b>{social?"6,8 % d’engagement":"12 840 leads générés"}</b><span>{social?"+1,4 pt ce mois":"Coût moyen 8,42 €"}</span></div></section><section className="em-card glass-panel"><div className="em-card-head"><span>À PUBLIER</span><button><Plus/></button></div>{[["LinkedIn","Étude : PME & agents IA","Aujourd’hui 17:30"],["Instagram","Carousel productivité","Demain 09:00"],["Email","Newsletter d’août","Vendredi 10:00"]].map(([channel,title,date])=><div className="content-row" key={title}><i><Megaphone/></i><span><b>{title}</b><small>{channel} · {date}</small></span><button><MoreHorizontal/></button></div>)}</section><section className="em-card glass-panel"><div className="em-card-head"><span>AUDIENces</span><em>486 204 profils</em></div>{[["Décideurs PME","128 k","76%"],["Clients actifs","24 k","42%"],["Prospects chauds","8 420","64%"]].map(([name,count,p])=><div className="campaign-row" key={name}><span><b>{name}</b><small>{count}</small></span><i><b style={{width:p}}/></i><em>{p}</em></div>)}</section></div>}

function FinanceView(){return <div className="em-grid"><section className="em-card glass-panel span-2"><div className="em-card-head"><span>TRÉSORERIE PRÉVISIONNELLE</span><button>12 mois <ChevronRight/></button></div><Sparkline/><div className="chart-caption"><b>184 200 € disponibles</b><span>Point bas prévu : 142 800 € en octobre</span></div></section><section className="em-card glass-panel"><div className="em-card-head"><span>À VALIDER</span><em>3 éléments</em></div>{[["Paiement fournisseur","2 840 €","Atelier Nord"],["Note de frais","486 €","Julien Morel"],["Abonnement annuel","1 200 €","Figma"]].map(([name,value,who])=><div className="finance-row" key={name}><span><b>{name}</b><small>{who}</small></span><strong>{value}</strong><button><Check/></button></div>)}</section><section className="em-card glass-panel"><div className="em-card-head"><span>RÉPARTITION DES DÉPENSES</span></div><div className="finance-donut"><i/><strong>86 k€<small>ce mois</small></strong></div><div className="mini-legend"><span><i/>Salaires 48%</span><span><i/>Marketing 22%</span><span><i/>Outils 18%</span><span><i/>Autres 12%</span></div></section></div>}

function PredictView(){return <div className="predict-grid">{[["risk","Risque trésorerie","Votre trésorerie pourrait passer sous 130 000 € dans 47 jours.","Impact élevé","Voir la simulation"],["opportunity","Opportunité commerciale","127 anciens prospects présentent une forte probabilité de conversion.","Potentiel 84 000 €","Lancer un plan"],["warning","Anomalie fournisseurs","Les coûts logistiques ont augmenté de 18 % sur deux semaines.","À analyser","Comparer"],["success","Prévision ventes","Le trimestre devrait dépasser l’objectif de 11,4 % au rythme actuel.","Confiance 91 %","Voir les facteurs"]].map(([tone,title,text,impact,action])=><article className={`glass-panel ${tone}`} key={title}><header><i>{tone==="risk"?<AlertTriangle/>:tone==="opportunity"?<Sparkles/>:tone==="success"?<TrendingUp/>:<Activity/>}</i><em>{impact}</em></header><h2>{title}</h2><p>{text}</p><button>{action}<ArrowRight/></button></article>)}</div>}

function ManagerView(){return <div className="manager-layout"><section className="manager-objective glass-panel"><span>OBJECTIF CEO</span><h2>Augmenter les ventes de 20 % ce trimestre.</h2><div className="manager-flow"><i><Image src="/brand/nova-app-icon.png" width={64} height={64} alt="Nova Manager"/></i><span><b>NOVA MANAGER</b><small>Plan généré · 7 agents coordonnés</small></span><em>En cours</em></div>{["Analyser les ventes et segments rentables","Identifier 127 opportunités prioritaires","Augmenter la prospection de 35 %","Lancer une campagne multicanale","Réactiver les anciens prospects","Optimiser les pages de conversion","Mesurer les résultats chaque semaine"].map((x,i)=><div className="manager-step" key={x}><i>{i<3?<Check/>:i+1}</i><span><b>{x}</b><small>{["Data Analyst","Nova SDR","Sales Agent","Marketing Agent"][i%4]}</small></span><em>{i<3?"Terminé":i===3?"En cours":"Planifié"}</em></div>)}</section><aside><section className="em-card glass-panel"><div className="em-card-head"><span>ÉQUIPE MOBILISÉE</span></div>{["Sales Agent","Nova SDR","Marketing Agent","Data Analyst","Customer Success"].map((name,i)=><div className="content-row" key={name}><i><Bot/></i><span><b>{name}</b><small>{["12 tâches","247 appels","3 campagnes","4 analyses","18 clients"][i]}</small></span><em>Actif</em></div>)}</section><section className="em-card glass-panel"><div className="em-card-head"><span>PROGRESSION</span><em>68 %</em></div><div className="manager-progress"><i><b/></i><strong>12 jours<small>avant le prochain jalon</small></strong></div></section></aside></div>}

function AutopilotView(){const [mode,setMode]=useState("Assisté");return <div className="autopilot-layout"><section className="autopilot-hero glass-panel"><div className={`autopilot-core ${mode.toLowerCase()}`}><Image src="/brand/nova-app-icon.png" width={110} height={110} alt="Autopilot NOVA"/><i/><i/></div><span>MODE ACTUEL</span><h2>{mode}</h2><p>{mode==="Copilot"?"Nova conseille uniquement. Aucune action n’est exécutée.":mode==="Assisté"?"Nova prépare les actions et demande votre confirmation.":mode==="Semi-autonome"?"Nova exécute seule les actions à faible risque.":"Nova fonctionne seule dans toutes les limites autorisées."}</p><div className="mode-selector">{["Copilot","Assisté","Semi-autonome","Autopilot"].map(x=><button className={mode===x?"active":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><button className="pause-nova"><Pause/> PAUSE NOVA</button></section><section className="autopilot-rules glass-panel"><header><div><ShieldCheck/><span><b>Limites d’autonomie</b><small>Règles actives pour tous les agents</small></span></div><button>Modifier</button></header>{[["Dépenses inférieures à 500 €","Automatique","good"],["Dépenses supérieures à 500 €","Validation","warn"],["Remboursement inférieur à 100 €","Automatique","good"],["Signature d’un contrat","Validation obligatoire","warn"],["Suppression de données","Interdit","bad"],["Publication sur les réseaux","Validation","warn"]].map(([name,status,tone])=><div className="rule-row" key={name}><span>{name}</span><em className={tone}>{status}</em></div>)}</section></div>}

function StoreView(){const agents=[["Nova SDR","Prospection","4,9","2 481","49 €"],["Nova Support","Service client","4,8","1 924","69 €"],["Nova CFO","Finance","4,9","986","89 €"],["Nova Recruiter","RH","4,7","742","59 €"],["Community Manager","Marketing","4,8","1 284","49 €"],["Operations Manager","Opérations","4,9","624","99 €"]];return <div className="agent-store-grid">{agents.map(([name,cat,rating,users,price],i)=><article className="glass-panel" key={name}><header><i><Bot/></i><em>{i<2?"POPULAIRE":"CERTIFIÉ"}</em></header><span>{cat}</span><h2>{name}</h2><p>Agent préconfiguré avec objectifs, compétences et workflows adaptés à votre entreprise.</p><div><span><Star/> {rating}</span><span><Users/> {users}</span></div><footer><b>{price}<small>/mois</small></b><button>Ajouter <Plus/></button></footer></article>)}</div>}

function ComputerView(){return <div className="computer-layout"><section className="computer-screen glass-panel"><header><i/><i/><i/><span>Session NOVA · Chrome</span><em>EN DIRECT</em></header><div className="fake-browser"><nav><ChevronRight/><span>app.hubspot.com/contacts</span><ShieldCheck/></nav><div className="browser-content"><aside/><main><span/><span/><div/><div/><div/><div/></main><div className="nova-cursor"><Image src="/brand/nova-app-icon.png" width={34} height={34} alt="Curseur NOVA"/><span>Nova enrichit 24 contacts…</span></div></div></div><footer><button><Pause/> Pause</button><button><Monitor/> Prendre le contrôle</button><span><i/> Session supervisée</span></footer></section><aside className="computer-log glass-panel"><div className="em-card-head"><span>ACTIONS EN DIRECT</span><em>18 terminées</em></div>{["Connexion à HubSpot","Ouverture de la liste Prospects Q3","Analyse de 24 contacts","Enrichissement des fonctions","Mise à jour du lead scoring","Préparation de la prochaine action"].map((x,i)=><div className={i<4?"done":i===4?"current":""} key={x}><i>{i<4?<Check/>:i+1}</i><span><b>{x}</b><small>{i<4?`${i+1} min`:i===4?"En cours":"En attente"}</small></span></div>)}</aside></div>}

function KnowledgeView(){return <div className="knowledge-grid">{[[FileText,"Documents","8 420 éléments","Synchronisé il y a 4 min"],[Globe2,"Sites web","1 284 pages","12 domaines"],[Users,"Clients","4 682 profils","CRM connecté"],[Package,"Produits & services","284 fiches","98 % complètes"],[Brain,"Procédures","148 processus","7 à réviser"],[MessageCircle,"FAQ & support","2 840 réponses","94 % couverture"]].map(([Icon,name,count,note])=><article className="glass-panel" key={name as string}><i><Icon/></i><span><b>{name as string}</b><small>{count as string}</small></span><em>{note as string}</em><button><ChevronRight/></button></article>)}</div>}

function SubscriptionView(){return <div className="subscription-layout"><section className="subscription-plan glass-panel"><span>OFFRE ACTUELLE</span><h2>NOVA Business</h2><p>Pour les équipes qui automatisent leurs opérations quotidiennes.</p><b>349 €<small>/ mois</small></b><button>Gérer l’abonnement</button></section><section className="subscription-usage glass-panel"><div className="em-card-head"><span>UTILISATION DU MOIS</span><em>Renouvellement dans 18 jours</em></div>{[["Crédits IA","72 %","7,2 M / 10 M"],["Minutes Voice","43 %","4 260 / 10 000"],["Automatisations","61 %","12 480 / 20 000"],["Stockage","28 %","28 Go / 100 Go"]].map(([name,p,value])=><div key={name}><span><b>{name}</b><small>{value}</small></span><i><b style={{width:p}}/></i><em>{p}</em></div>)}</section></div>}

function ModuleBody({kind}:{kind:string}){if(kind==="voice")return <VoiceView/>;if(kind==="crm")return <LiveCrm demoFallback={<DemoCRMView/>}/>;if(kind==="projects")return <DemoCRMView/>;if(kind==="prospecting")return <LiveProspecting demoFallback={<div className="em-grid"><GenericTable kind="prospecting"/></div>}/>;if(kind==="marketing")return <MarketingView/>;if(kind==="social")return <MarketingView social/>;if(kind==="finance")return <FinanceView/>;if(kind==="predict")return <PredictView/>;if(kind==="manager")return <ManagerView/>;if(kind==="autopilot")return <AutopilotView/>;if(kind==="store")return <StoreView/>;if(kind==="computer")return <ComputerView/>;if(kind==="knowledge")return <KnowledgeView/>;if(kind==="subscription")return <SubscriptionView/>;if(kind==="communications")return <div className="communications-preview"><GenericTable kind="support"/><Link href="/app/inbox">Ouvrir l’Inbox complète <ArrowRight/></Link></div>;if(["support","operations","hr"].includes(kind))return <div className="em-grid"><GenericTable kind={kind}/><section className="em-card glass-panel"><div className="em-card-head"><span>ÉVOLUTION</span><em>30 jours</em></div><Sparkline/><div className="chart-caption"><b>Performance en hausse</b><span>Analyse NOVA</span></div></section><section className="em-card glass-panel"><div className="em-card-head"><span>ACTIONS NOVA</span><em>EN DIRECT</em></div>{["Analyse des nouvelles données","Mise à jour des priorités","Préparation des prochaines actions","Contrôle des anomalies"].map((x,i)=><div className="content-row" key={x}><i>{i<2?<Check/>:<Sparkles/>}</i><span><b>{x}</b><small>{i<2?"Terminé":"En cours"}</small></span></div>)}</section></div>;return null}

export function EnterpriseModulePage({slug}:{slug:string}){const config=moduleConfigs[slug];const [tab,setTab]=useState(config?.tabs[0]||"");if(!config)return <div className="product-page"><h1>Module introuvable</h1></div>;return <div className={`product-page enterprise-module module-${config.kind}`}><header className="em-title"><div><span>{config.eyebrow}</span><h1>{config.title}</h1><p>{config.description}</p></div><div><button><CalendarClock/> Aujourd’hui</button><button className="product-primary"><Sparkles/> Demander à Nova</button></div></header><nav className="em-tabs" aria-label={`Navigation ${config.title}`}>{config.tabs.map(item=><button className={tab===item?"active":""} onClick={()=>setTab(item)} key={item}>{item}</button>)}</nav><div className="em-context"><span>{tab}</span><i/><b>Données de démonstration</b><em>Interface front-end</em></div><MetricCards items={config.metrics}/><ModuleBody kind={config.kind}/></div>}
