"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { motion, useInView } from "motion/react";
import { ArrowRight, BarChart3, Check, ChevronDown, Mic, MoreVertical, Paperclip, Play, RotateCcw, Send, ShieldCheck, Sparkles, Users } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";

const NovaScene = dynamic(() => import("./scene"), { ssr: false, loading: () => <div className="scene-loader"><i/><span>NOVA s’éveille</span></div> });

export function Reveal({ children, className = "" }: { children: React.ReactNode; className?: string }) { const ref = useRef(null); const visible = useInView(ref, { once: true, margin: "-80px" }); return <motion.div ref={ref} className={className} initial={{ opacity: 0, y: 34 }} animate={visible ? { opacity: 1, y: 0 } : {}} transition={{ duration: .75, ease: [.2,.8,.2,1] }}>{children}</motion.div>; }

export function Hero() { return <section className="hero shell"><div className="hero-copy"><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="status-pill"><i/> Intelligence opérationnelle · Accès anticipé</motion.div><motion.h1 initial={{opacity:0,y:26}} animate={{opacity:1,y:0}} transition={{delay:.1}}>Un vocal.<br/><span>Toute votre entreprise</span><br/>s’exécute.</motion.h1><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}>NOVA comprend votre demande, orchestre ses agents IA et coordonne vos outils. Vous gardez le dernier mot.</motion.p><motion.div className="hero-actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.35}}><Link className="button primary" href="#demo">Essayer Nova <ArrowRight/></Link><Link className="button ghost" href="#fonctionnement"><Play/> Voir comment ça marche</Link></motion.div><div className="trust-line"><ShieldCheck/> Actions sensibles soumises à vos règles d’approbation</div></div><div className="hero-visual" aria-label="Visualisation 3D du cœur NOVA"><div className="scene"><NovaScene/></div><div className="orbit-label l1">Finance <i/></div><div className="orbit-label l2">Marketing <i/></div><div className="orbit-label l3">Sales <i/></div><div className="core-caption"><span>NOVA CORE</span><strong>8 agents synchronisés</strong></div></div></section>; }

const demoTasks = ["CRM analysé", "Prospects identifiés", "Relances préparées", "Reporting généré", "Équipe informée"];
export function NovaDemo() {
  const [query,setQuery] = useState("Relance mes prospects et prépare mon reporting."); const [running,setRunning] = useState(false); const [done,setDone] = useState(0);
  useEffect(() => { if (!running || done >= demoTasks.length) return; const t=setTimeout(()=>setDone(d=>d+1),650); return()=>clearTimeout(t); },[running,done]);
  function run(){ if(!query.trim()) return; setDone(0); setRunning(true); }
  return <section id="demo" className="section dark"><div className="shell demo-grid"><Reveal><span className="eyebrow light">Démonstration interactive</span><h2>Une intention.<br/><em>Une entreprise en mouvement.</em></h2><p>Écrivez comme vous parlez. NOVA transforme votre demande en un plan d’action orchestré.</p><span className="demo-disclaimer">Simulation produit — aucune action réelle n’est envoyée.</span></Reveal><Reveal className="demo-console"><div className="console-top"><span><i/> NOVA / ORCHESTRATEUR</span><span>MODE DÉMO</span></div><div className="command-box"><textarea aria-label="Votre demande" value={query} onChange={e=>setQuery(e.target.value)} rows={2}/><button onClick={run} aria-label="Lancer la démonstration"><Send/></button></div><div className="task-list">{running && <div className={`analyse ${done===demoTasks.length?"complete":""}`}><Sparkles/> {done===demoTasks.length?"Demande orchestrée":"NOVA analyse votre demande…"}</div>}{demoTasks.map((task,i)=><div className={`task ${i<done?"done":""}`} key={task}><span>{i<done?<Check/>:<i/>}</span>{task}<small>{i<done?"TERMINÉ":"EN ATTENTE"}</small></div>)}</div></Reveal></div></section>;
}

export function VoiceFlow() { const agents=["CRM","Finance","Social","Analytics"]; return <section className="section voice-section"><div className="shell"><Reveal className="section-heading centered"><span className="eyebrow">Le nouveau geste du dirigeant</span><h2>Parlez à Nova.<br/><em>Nova s’occupe du reste.</em></h2></Reveal><Reveal className="voice-flow"><div className="phone"><div className="phone-bar"><span>9:41</span><b>WhatsApp</b><span>•••</span></div><div className="chat"><small>Aujourd’hui, 09:41</small><div className="bubble user"><p>Nova, relance les prospects qui n’ont pas répondu, prépare le reporting et programme une publication.</p><div className="wave"><button aria-label="Lecture"><Play/></button>{Array.from({length:22},(_,i)=><i key={i} style={{height:`${10+(i*17)%28}px`}}/>)}<span>0:12</span></div></div><div className="bubble nova">Bien reçu. Je coordonne les agents et vous demande confirmation avant tout envoi sensible.<span>09:42 ✓✓</span></div></div></div><div className="flow-center"><div className="voice-beam"><Mic/><span/><span/><span/></div><div className="mini-core"><Sparkles/><b>NOVA</b><small>INTENTION COMPRISE</small></div></div><div className="agent-stack">{agents.map((agent,i)=><div className="agent-task" key={agent} style={{"--delay":`${i*.12}s`} as React.CSSProperties}><span>0{i+1}</span><div><b>Nova {agent}</b><small>{["12 prospects à qualifier","4 factures à vérifier","Publication préparée","Rapport assemblé"][i]}</small></div><Check/></div>)}</div></Reveal></div></section>; }

const weeklyMessages: Array<{agent:string;initials:string;color:string;text:string;time:string;owner?:boolean;executive?:boolean}> = [
  {agent:"Gérant", initials:"GN", color:"#1d1d21", text:"Bonjour l’équipe. Débrief de la semaine : qu’est-ce qui a avancé, où sont les risques et que dois-je décider lundi ?", time:"17:30", owner:true},
  {agent:"Nova Sales", initials:"NS", color:"#6d4aff", text:"47 nouveaux leads analysés. J’en ai qualifié 18, obtenu 9 rendez-vous et préparé 3 propositions pour 28 400 €. Deux opportunités Enterprise sont bloquées sur la validation sécurité.", time:"17:30"},
  {agent:"Nova Marketing", initials:"NM", color:"#ed4eb5", text:"La campagne “Une seule intelligence” a généré 126 demandes à un coût par lead inférieur de 18 % à la semaine dernière. Le post LinkedIn sur les agents Finance atteint 8,7 % d’engagement. Je recommande d’en faire une série mardi.", time:"17:31"},
  {agent:"Nova Finance", initials:"NF", color:"#279b70", text:"14 factures ont été rapprochées, 11 sont réglées. Deux retards totalisent 6 850 € : les relances sont prêtes mais attendent votre accord. La trésorerie projetée reste au-dessus du seuil de sécurité sur les 12 prochaines semaines.", time:"17:31"},
  {agent:"Nova Support", initials:"SU", color:"#e18a32", text:"86 demandes traitées, temps de première réponse médian : 11 min. Un motif revient sur 7 tickets — le délai d’activation HubSpot. J’ai préparé une réponse proactive et transmis le problème à Operations.", time:"17:32"},
  {agent:"Nova Operations", initials:"NO", color:"#3977d8", text:"Le délai d’activation vient d’un contrôle manuel en double. J’ai cartographié le blocage : sa suppression ferait gagner environ 6 h par semaine. Le nouveau workflow est prêt en environnement de test, sans modification en production.", time:"17:32"},
  {agent:"Nova Executive", initials:"NX", color:"#7b45ff", text:"Synthèse : 3 décisions lundi — approuver les relances de 6 850 €, valider la série LinkedIn et autoriser le test du nouveau workflow HubSpot. Priorité recommandée : débloquer les 2 opportunités Enterprise avant mardi 12 h.", time:"17:33", executive:true},
];

export function WeeklyDebrief() {
  const ref=useRef<HTMLElement>(null); const inView=useInView(ref,{once:true,margin:"-120px"}); const [visible,setVisible]=useState(0); const [cycle,setCycle]=useState(0);
  useEffect(()=>{if(!inView)return;const timers=[setTimeout(()=>setVisible(0),0),...weeklyMessages.map((_,i)=>setTimeout(()=>setVisible(i+1),400+i*980))];return()=>timers.forEach(clearTimeout)},[inView,cycle]);
  return <section ref={ref} className="section weekly-section"><div className="shell"><Reveal className="section-heading split"><div><span className="eyebrow light">Le vendredi, 17:30</span><h2>Toute votre équipe IA.<br/><em>Dans le même groupe.</em></h2></div><p>Les agents ne travaillent pas en silos. Ils partagent leurs résultats, signalent les risques et préparent les décisions de la semaine suivante.</p></Reveal><div className="weekly-stage"><div className="weekly-phone"><div className="wa-header"><div className="group-avatar"><span>N</span><i/><i/><i/></div><div><b>NOVA · Comité hebdo</b><small>Gérant, Executive, Sales, Marketing, Finance, Support, Operations</small></div><MoreVertical/></div><div className="wa-date">VENDREDI</div><div className="weekly-feed">{weeklyMessages.map((m,i)=><motion.div initial={{opacity:0,y:16,scale:.98}} animate={i<visible?{opacity:1,y:0,scale:1}:{}} transition={{duration:.45}} className={`weekly-message ${m.owner?"owner":""} ${m.executive?"executive":""}`} key={m.agent}><span className="agent-avatar" style={{background:m.color}}>{m.initials}</span><div><b style={{color:m.color}}>{m.agent}</b><p>{m.text}</p><small>{m.time}{m.owner?"  ✓✓":""}</small></div></motion.div>)}{visible<weeklyMessages.length&&visible>0?<div className="typing"><i/><i/><i/><span>{weeklyMessages[visible]?.agent} écrit…</span></div>:null}</div><div className="wa-input"><button aria-label="Joindre un fichier"><Paperclip/></button><span>Répondre au groupe</span><button aria-label="Message vocal"><Mic/></button></div></div><aside className="weekly-summary"><div className="summary-live"><i/> DÉBRIEF SYNCHRONISÉ</div><h3>La semaine,<br/>en un coup d’œil.</h3><div className="summary-metric"><span><Users/> Pipeline</span><strong>28,4 k€</strong><small>3 propositions préparées</small></div><div className="summary-metric"><span><BarChart3/> Acquisition</span><strong>−18 %</strong><small>coût par lead vs S-1</small></div><div className="summary-metric"><span><ShieldCheck/> Décisions</span><strong>3</strong><small>validations attendues lundi</small></div><div className="decision-card"><span>PRIORITÉ LUNDI</span><b>Débloquer les opportunités Enterprise</b><small>Échéance recommandée · 12:00</small></div><button className="replay-button" onClick={()=>setCycle(c=>c+1)}><RotateCcw/> Rejouer le débrief</button><p>Démonstration animée — données d’entreprise simulées.</p></aside></div></div></section>;
}

export function PageHero({ kicker, title, accent, text }: { kicker:string; title:string; accent:string; text:string }) { return <section className="page-hero shell"><Reveal><span className="eyebrow">{kicker}</span><h1>{title}<br/><em>{accent}</em></h1><p>{text}</p></Reveal><div className="page-orb"><NovaScene/></div></section>; }

export function CTA({ title="Votre prochaine action commence ici.", text="Décrivez un objectif. NOVA prépare le chemin.", href="/#demo", label="Découvrir Nova" }: {title?:string;text?:string;href?:string;label?:string}) { return <section className="section"><Reveal className="cta shell"><span className="eyebrow light">NOVA</span><h2>{title}</h2><p>{text}</p><Link className="button white" href={href}>{label}<ArrowRight/></Link></Reveal></section>; }

export function FAQ({ items }: { items: [string,string][] }) { const [open,setOpen]=useState(0); return <div className="faq">{items.map(([q,a],i)=><div className={`faq-item ${open===i?"open":""}`} key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><ChevronDown/></button><div><p>{a}</p></div></div>)}</div>; }

export function LeadForm({ kind="contact" }: {kind?:string}) { const [status,setStatus]=useState<"idle"|"error"|"ready">("idle"); function submit(e:FormEvent<HTMLFormElement>){e.preventDefault(); const fd=new FormData(e.currentTarget); if(!fd.get("email")?.toString().includes("@")){setStatus("error");return;} setStatus("ready");} return <form className="lead-form" onSubmit={submit} noValidate><div className="form-row"><label>Prénom<input name="name" required placeholder="Votre prénom"/></label><label>Email professionnel<input name="email" type="email" required placeholder="vous@entreprise.com"/></label></div><label>Entreprise<input name="company" placeholder="Nom de l’entreprise"/></label><label>Votre message<textarea name="message" rows={4} placeholder={kind==="investor"?"Présentez-vous en quelques mots":"Que souhaitez-vous automatiser ?"}/></label><button className="button primary" type="submit">{kind==="investor"?"Recevoir le dossier":"Envoyer la demande"}<ArrowRight/></button>{status==="error"&&<p className="form-state error">Saisissez une adresse email valide.</p>}{status==="ready"&&<p className="form-state success">Formulaire validé. L’envoi sera activé dès la configuration du service de messagerie.</p>}</form>; }
