export type ModuleStatus = "WORKING" | "PARTIAL" | "DEMO" | "MISSING" | "BLOCKED";
export type ModuleAudit = { module:string; status:ModuleStatus; frontend:boolean; backend:boolean; database:boolean; ai:boolean; integration:boolean; notes:string };

const demo = (module:string, notes:string):ModuleAudit => ({module,status:"DEMO",frontend:true,backend:false,database:false,ai:false,integration:false,notes});

export function getModuleAudit(): ModuleAudit[] {
  const database=Boolean(process.env.DATABASE_URL); const crmValidated=database&&process.env.NOVA_CRM_VALIDATED==="true";
  const authConfigured=database&&Boolean(process.env.BETTER_AUTH_SECRET); const saasValidated=authConfigured&&process.env.NOVA_SAAS_VALIDATED==="true";
  const onboardingValidated=saasValidated&&process.env.NOVA_ONBOARDING_VALIDATED==="true";const industryValidated=onboardingValidated&&process.env.NOVA_INDUSTRY_VALIDATED==="true";const ai=Boolean(process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN||process.env.NOVA_GATEWAY_READY==="true");const aiValidated=industryValidated&&ai&&process.env.NOVA_AI_VALIDATED==="true";const actionValidated=saasValidated&&process.env.NOVA_ACTIONS_VALIDATED==="true";const workflowValidated=actionValidated&&process.env.NOVA_WORKFLOW_VALIDATED==="true";
  return [
    demo("Accueil","Dashboard visuel alimenté par des données de démonstration."),
    {module:"Nova",status:aiValidated?"WORKING":ai?"PARTIAL":"BLOCKED",frontend:true,backend:ai,database,ai,integration:false,notes:aiValidated?"Nova AI Core read-only, contexte tenant, outils CRM et conversations persistantes validés.":"AI Core installé ; validation E2E requise."},
    demo("Nova Manager","Plans, agents, KPI et résultats simulés."),demo("Autopilot","Modes et permissions limités à l’état React local."),
    {module:"Prospection",status:crmValidated?"WORKING":"BLOCKED",frontend:true,backend:database,database,ai:false,integration:false,notes:crmValidated?"CRUD PostgreSQL validé en production : création, refresh, recherche, filtre, modification et suppression E2E réussis.":database?"CRUD PostgreSQL installé ; validation E2E requise.":"Couche CRUD prête, nécessite DATABASE_URL et migration."},
    {module:"Ventes / CRM",status:crmValidated?"WORKING":"BLOCKED",frontend:true,backend:database,database,ai:false,integration:false,notes:crmValidated?"CRUD et Kanban PostgreSQL validés en production : persistance après refresh et scénarios CRM-A à CRM-E réussis.":database?"CRUD et Kanban PostgreSQL installés ; validation E2E requise.":"Couche CRUD prête, nécessite DATABASE_URL et migration."},
    demo("Marketing","Campagnes, audiences et graphiques simulés."),demo("Communications","Inbox et messages fictifs, aucun canal connecté."),demo("Réseaux sociaux","Publications et métriques simulées."),demo("Service client","Tickets et satisfaction simulés."),demo("Nova Voice","Appels, voix et campagnes simulés."),demo("Finance","Trésorerie, paiements et dépenses simulés."),demo("RH","Collaborateurs, candidatures et présence simulés."),demo("Opérations","Commandes, stocks et incidents simulés."),demo("Tâches & Projets","Pipeline visuel sans stockage serveur."),demo("Documents","État vide réel, import et stockage absents."),demo("Agents IA","Profils d’agents visuels sans runtime métier autonome."),demo("Automatisations","Scénarios visuels sans moteur d’exécution ni planificateur."),demo("Analytics","Graphiques et métriques de démonstration."),demo("Nova Predict","Prévisions et anomalies fictives."),demo("Connaissances","Sources et indexation simulées."),demo("Computer Agent","Session navigateur et actions simulées."),
    {module:"Authentication",status:saasValidated?"WORKING":authConfigured?"PARTIAL":"BLOCKED",frontend:true,backend:authConfigured,database:authConfigured,ai:false,integration:false,notes:saasValidated?"Better Auth email/mot de passe, sessions, logout et protections validés. Reset email et Google OAuth non configurés.":"Better Auth installé ; validation E2E requise."},
    {module:"Organizations",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:saasValidated?"Création et paramètres d’entreprise persistants validés.":"Schéma et API installés."},
    {module:"Memberships",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:saasValidated?"Memberships multi-organisations et dernier Owner protégés.":"Schéma et API installés."},
    {module:"Multi-tenancy",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:saasValidated?"Isolation session → membership → organisation validée contre cross-tenant et IDOR.":"Contextualisation serveur installée ; validation requise."},
    {module:"Permissions",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:saasValidated?"Matrice OWNER/ADMIN/MANAGER/MEMBER/VIEWER validée côté serveur.":"Matrice centralisée installée."},
    {module:"Invitations",status:"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Création, token hashé, expiration et acceptation disponibles. Envoi email BLOCKED faute de provider."},
    {module:"Audit Log",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:saasValidated?"Événements sensibles enregistrés par organisation et visibles dans Security Center.":"Journal installé ; validation requise."},
    {module:"Intégrations",status:"BLOCKED",frontend:true,backend:false,database:false,ai:false,integration:false,notes:"Catalogue disponible ; OAuth, comptes fournisseurs et secrets requis."},
    demo("Agent Store","Catalogue, notes, prix et installations simulés."),
    {module:"Sécurité",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:authConfigured,ai:false,integration:false,notes:saasValidated?"Security Center réel : session, membres, rôles, permissions et audit logs. 2FA/SSO Coming Soon.":"Fondations auth et sécurité installées ; validation E2E requise."},
    {module:"Abonnement",status:"BLOCKED",frontend:true,backend:false,database:false,ai:false,integration:false,notes:"Interface de démonstration ; Stripe et webhooks requis."},
    {module:"Paramètres",status:saasValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:authConfigured,ai, integration:false,notes:saasValidated?"Profil, Company Profile et configuration Nova persistants et scellés au tenant actif.":"Formulaires persistants installés ; validation requise."},
    {module:"Onboarding",status:onboardingValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:onboardingValidated?"Flux 8 étapes, reprise durable et complétion validés en production.":"Flux installé ; validation E2E requise."},
    {module:"Company Profile",status:onboardingValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:"Contexte métier structuré et isolé par organisation."},
    {module:"Workspace Configuration",status:onboardingValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:"Modules et souhaits persistants ; intégrations souhaitées explicitement non connectées."},
    {module:"Recommendation Engine",status:onboardingValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:false,ai:false,integration:false,notes:"Moteur déterministe, extensible et sans faux appel IA."},
    {module:"Industry Engine",status:industryValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:false,ai:false,integration:false,notes:"Sept templates typés, aliases, sous-secteurs, objectifs et overrides manuels."},
    {module:"Adaptive Navigation",status:industryValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:"Ordre sectoriel, terminologie et More / All Modules par organisation."},
    {module:"Adaptive Dashboard",status:industryValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:"Dashboard dynamique avec Contacts et Deals réels."},
    {module:"Widget Registry",status:industryValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:false,ai:false,integration:false,notes:"Widgets LIVE, DEMO, NOT_CONNECTED et COMING_SOON séparés."},
    {module:"Workspace Customization",status:industryValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:false,integration:false,notes:"Ordre, visibilité, widgets et reset persistants."},
    {module:"Terminology Engine",status:industryValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:false,ai:false,integration:false,notes:"Terminologie d’affichage adaptée sans modifier le schéma."},
    {module:"Nova AI Core",status:aiValidated?"WORKING":"PARTIAL",frontend:true,backend:ai,database,ai,integration:false,notes:"Streaming, contexte d’entreprise, limites et mode strictement read-only."},
    {module:"AI Provider",status:aiValidated?"WORKING":ai?"PARTIAL":"BLOCKED",frontend:false,backend:ai,database:false,ai,integration:ai,notes:"Abstraction Vercel AI Gateway, profils FAST/REASONING et modèle gratuit configuré."},
    {module:"Context Engine",status:aiValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database,ai:false,integration:false,notes:"Organization, Company Profile, Workspace, Industry et permissions ciblés."},
    {module:"Tool Registry",status:aiValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:true,integration:false,notes:"Registre typé avec permission, risque et mode pour chaque outil."},
    {module:"Read-Only Business Tools",status:aiValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:true,integration:false,notes:"Company, Contacts, Pipeline, Deals, Workspace et Business Brief, toujours scellés au tenant."},
    {module:"Conversations",status:aiValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database,ai:true,integration:false,notes:"Historique PostgreSQL privé par utilisateur et organisation."},
    {module:"AI Usage Tracking",status:aiValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database,ai:true,integration:false,notes:"Tokens provider, modèle, latence et coût null lorsqu’il n’est pas fiable."},
    {module:"Action Engine",status:actionValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Moteur centralisé de demandes WRITE, revalidation serveur et exécution contrôlée."},
    {module:"Action Registry",status:actionValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:false,ai:false,integration:false,notes:"Actions CRM déclaratives avec permission, risque et politique d’approbation."},
    {module:"Risk Engine",status:actionValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:false,ai:false,integration:false,notes:"Évaluation déterministe LOW/MEDIUM/HIGH/CRITICAL."},
    {module:"Approval Center",status:actionValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Revue, approbation, rejet, expiration et aperçu des actions."},
    {module:"Idempotency Protection",status:actionValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:true,ai:false,integration:false,notes:"Claim atomique empêchant la double exécution d'une action."},
    {module:"Workflow Engine",status:workflowValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Runtime déterministe de workflows multi-tenant."},
    {module:"Business Event Bus",status:workflowValidated?"WORKING":"PARTIAL",frontend:false,backend:database,database,ai:false,integration:false,notes:"Événements métier persistants et idempotents."},
    {module:"Trigger Registry",status:workflowValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:false,ai:false,integration:false,notes:"Triggers CRM initiaux déclarés."},
    {module:"Condition Engine",status:workflowValidated?"WORKING":"PARTIAL",frontend:true,backend:true,database:false,ai:false,integration:false,notes:"Opérateurs déterministes sans eval ni JavaScript arbitraire."},
    {module:"Automation Runtime",status:workflowValidated?"WORKING":"PARTIAL",frontend:false,backend:database,database,ai:false,integration:false,notes:"Runs, step runs, erreurs et statuts persistants."},
    {module:"Automation Builder",status:workflowValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Création structurée de workflows et déclencheurs."},
    {module:"Run History",status:workflowValidated?"WORKING":"PARTIAL",frontend:true,backend:database,database,ai:false,integration:false,notes:"Historique des exécutions par organisation."},
    {module:"Loop Protection",status:workflowValidated?"WORKING":"PARTIAL",frontend:false,backend:true,database:false,ai:false,integration:false,notes:"Protection de profondeur et idempotence en préparation du runtime complet."},
  ];
}

const weights:Record<ModuleStatus,number>={WORKING:1,PARTIAL:.6,DEMO:.2,MISSING:0,BLOCKED:0};
export function calculateProgress(modules:ModuleAudit[]){return Math.round(modules.reduce((sum,item)=>sum+weights[item.status],0)/modules.length*100)}
export const progressFormula="WORKING 100 % · PARTIAL 60 % · DEMO 20 % · MISSING/BLOCKED 0 %";
